### ISSUE TITLE
Unable to Use '%' Sign in Database Password

### ISSUE THREAD

**Issue by Trinkes** [langflow-ai/langflow#1528]
**Describe the bug**
I've encountered an issue where I'm unable to use the '%' sign in my database password. This problem has been discussed in the Alembic repository ([Issue #700](https://github.com/sqlalchemy/alembic/issues/700)), where it's noted that Alembic doesn't allow '%' signs in the password.

To work around this limitation, it's suggested to use urllib.parse.quote_plus to encode the password and replace the '%' with '%%' as described in [this comment](https://github.com/sqlalchemy/alembic/issues/700#issuecomment-636020804). However, this workaround results in an incorrect password in the SQLAlchemy context.

**Steps to reproduce:**

1. Attempt to use a database password containing the '%' sign in an Alembic migration or SQLAlchemy connection string.
2. Apply the suggested workaround of encoding the password with urllib.parse.quote_plus and replacing '%' with '%%'.
3. Note the behavior when attempting to use the password with both Alembic and SQLAlchemy.

**Expected behavior:**
The database password containing the '%' sign should be accepted and function properly in both Alembic and SQLAlchemy contexts.

**Actual behavior:**
Alembic does not allow the '%' sign in the password, and the suggested workaround results in an incorrect password in SQLAlchemy.

```text
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
      File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/user/.local/lib/python3.10/site-packages/langflow/main.py", line 20, in lifespan
    initialize_services()
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/utils.py", line 217, in initialize_services
    raise exc
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/utils.py", line 214, in initialize_services
    initialize_database(fix_migration=fix_migration)
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/database/utils.py", line 52, in initialize_database
    raise exc
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/database/utils.py", line 32, in initialize_database
    database_service.run_migrations(fix=fix_migration)
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/database/service.py", line 130, in run_migrations
    alembic_cfg.set_main_option("sqlalchemy.url", self.database_url)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/config.py", line 272, in set_main_option
    self.set_section_option(self.config_ini_section, name, value)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/config.py", line 299, in set_section_option
    self.file_config.set(section, name, value)
  File "/usr/local/lib/python3.10/configparser.py", line 1206, in set
    super().set(section, option, value)
  File "/usr/local/lib/python3.10/configparser.py", line 896, in set
    value = self._interpolation.before_set(self, section, option,
                                                                  File "/usr/local/lib/python3.10/configparser.py", line 403, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in 'postgresql://myuser:mypassword%s@langflow-postgres:5432/langflow' at position 30
```

**Browser and Version**
 - Browser [N/A]
 - Version [N/A]

**Screenshots**

**Additional context**
trying to setup and use langfuse using docker.

**Comment by Trinkes** [comment]
Isn't there a better way to do this other that editing the actual project's code?
if nothing else, can both urls (sqlachemy and alembic) can be exposed and set separately?

**Comment by ogabrielluiz** [comment]
Hey @Trinkes 

I think I like the idea of having different variables for both as an optional override. 
I'll look into that, probably today. If you think you could help or have any other input, please let me know.
