### ISSUE TITLE
Issue with npm install node-sass

### ISSUE THREAD

**Issue by deepsai8** [langflow-ai/langflow#1695]
**Describe the bug**
There appears to be an issue with npm install node-sass. Here are the key points from the error log:
- The command node scripts/build.js is failing while trying to build node-sass.
- The binary file binding.node is being tested, but it has a problem.
- The error message suggests that binding.node is not recognized as a valid Mach-O file, which is the format for binaries on macOS.

**Versions**
 - node -v v20.1.0
 - node-gyp -v v8.4.1
 - nvm -v v0.39.3
 - python --version v3.11.4

**To Reproduce**
Steps to reproduce the behavior, follow the steps to build documentation locally:
- cd docs
- npm install
- See error

**Additional context**
From the error log:
<details>
```
2035 verbose stack Error: command failed
2035 verbose stack     at ChildProcess.<anonymous> (/Users/user1/.nvm/versions/node/v21.7.3/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
2035 verbose stack     at ChildProcess.emit (node:events:519:28)
2035 verbose stack     at maybeClose (node:internal/child_process:1105:16)
2035 verbose stack     at Socket.<anonymous> (node:internal/child_process:457:11)
2035 verbose stack     at Socket.emit (node:events:519:28)
2035 verbose stack     at Pipe.<anonymous> (node:net:337:12)
2036 verbose pkgid node-sass@9.0.0
2037 verbose cwd /Users/user1/Desktop/experiments/langflow/docs
2038 verbose Darwin 23.4.0
2039 verbose node v21.7.3
2040 verbose npm  v10.5.2
2041 error code 1
2042 error path /Users/user1/Desktop/experiments/langflow/docs/node_modules/node-sass
2043 error command failed
2044 error command sh -c node scripts/build.js
2045 error Binary found at /Users/user1/Desktop/experiments/langflow/docs/node_modules/node-sass/vendor/darwin-arm64-120/binding.node
2045 error Testing binary
2045 error Binary has a problem: Error: dlopen(/Users/user1/Desktop/experiments/langflow/docs/node_modules/node-sass/vendor/darwin-arm64-120/binding.node, 0x0001): tried: '/Users/user1/Desktop/experiments/langflow/docs/node_modules/node-sass/vendor/darwin-arm64-120/binding.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/user1/Desktop/experiments/langflow/docs/node_modules/node-sass/vendor/darwin-arm64-120/binding.node' (no such file), '/Users/user1/Desktop/experiments/langflow/docs/node_modules/node-sass/vendor/darwin-arm64-120/binding.node' (not a mach-o file)
2045 error     at Module._extensions..node (node:internal/modules/cjs/loader:1464:18)
2045 error     at Module.load (node:internal/modules/cjs/loader:1205:32)
2045 error     at Module._load (node:internal/modules/cjs/loader:1021:12)
2045 error     at Module.require (node:internal/modules/cjs/loader:1230:19)
2045 error     at require (node:internal/modules/helpers:179:18)
2045 error     at module.exports (/Users/user1/Desktop/experiments/langflow/docs/node_modules/node-sass/lib/binding.js:19:10)
2045 error     at Object.<anonymous> (/Users/user1/Desktop/experiments/langflow/docs/node_modules/node-sass/lib/index.js:13:35)
2045 error     at Module._compile (node:internal/modules/cjs/loader:1368:14)
2045 error     at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
2045 error     at Module.load (node:internal/modules/cjs/loader:1205:32) {
2045 error   code: 'ERR_DLOPEN_FAILED'
2045 error }
```
</details>

**Workaround**
- Remove ln54 in `docs/package.json`, that is, remove `"node-sass": "^9.0.0",`

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.

**Comment by hfilmore** [comment]
In case anyone else has this issue I fixed it by installing **distutils** (`brew install python-setuptools`)
