### ISSUE TITLE
Clean install v1.0.0a28 - Migration Error

### ISSUE THREAD

**Issue by fcools** [langflow-ai/langflow#1797]
After a clean install of v1.0.0a28 with:
```
python -m pip install langflow --pre --force-reinstall
```
this error pops up:

```
Starting Langflow v1.0.0a28...
[04/30/24 11:26:53] ERROR    2024-04-30 11:26:53 - ERROR    - service - AutogenerateDiffsDetected: New upgrade operations detected: [[('modify_type', None, 'apikey', 'created_at',                service.py:171
                             {'existing_nullable': True, 'existing_server_default': DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7fa0fce6b850>, for_update=False),
                             'existing_comment': None}, TIMESTAMP(), DateTime(timezone=True)), ('modify_nullable', None, 'apikey', 'created_at', {'existing_type': TIMESTAMP(),
                             'existing_server_default': DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7fa0fce6b850>, for_update=False), 'existing_comment': None}, True, False)]]
                    ERROR    2024-04-30 11:26:53 - ERROR    - utils - Something went wrong running migrations. Please, run `langflow migration --fix`                                                 utils.py:51
Shutting down Langflow...
                    ERROR    2024-04-30 11:26:53 - ERROR    - on - Traceback (most recent call last):                                                                                                   on.py:121
                               File "/llm/langflow/langflow/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
                                 async with self.lifespan_context(app) as maybe_state:
                               File "/usr/lib/python3.10/contextlib.py", line 201, in __aenter__
                                 raise RuntimeError("generator didn't yield") from None
                             RuntimeError: generator didn't yield

                    ERROR    2024-04-30 11:26:53 - ERROR    - on - Application startup failed. Exiting.                                                                                                  on.py:59
[04/30/24 11:26:53] ERROR    2024-04-30 11:26:53 - ERROR    - glogging - Worker (pid:666513) exited with code 3                                                                                   glogging.py:272
                    ERROR    2024-04-30 11:26:53 - ERROR    - glogging - Shutting down: Master                                                                                                    glogging.py:272
                    ERROR    2024-04-30 11:26:53 - ERROR    - glogging - Reason: Worker failed to boot.                                                                                           glogging.py:272
```

The suggestion to run langflow migration --fix throws the following error:

```
2024-04-30 11:28:51.868 | INFO     | langflow.services.database.service:run_migrations:157 - Running DB migrations in /llm/langflow/langflow/lib/python3.10/site-packages/langflow/alembic
2024-04-30 11:28:54.918 | ERROR    | langflow.services.database.service:run_migrations:171 - AutogenerateDiffsDetected: New upgrade operations detected: [[('modify_type', None, 'apikey', 'created_at', {'existing_nullable': True, 'existing_server_default': DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f24008e6aa0>, for_update=False), 'existing_comment': None}, TIMESTAMP(), DateTime(timezone=True)), ('modify_nullable', None, 'apikey', 'created_at', {'existing_type': TIMESTAMP(), 'existing_server_default': DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f24008e6aa0>, for_update=False), 'existing_comment': None}, True, False)]]
2024-04-30 11:28:54.939 | WARNING  | langflow.services.database.service:try_downgrade_upgrade_until_success:189 - AutogenerateDiffsDetected: New upgrade operations detected: [[('modify_type', None, 'apikey', 'created_at', {'existing_nullable': True, 'existing_server_default': DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f24009449d0>, for_update=False), 'existing_comment': None}, TIMESTAMP(), DateTime(timezone=True)), ('modify_nullable', None, 'apikey', 'created_at', {'existing_type': TIMESTAMP(), 'existing_server_default': DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f24009449d0>, for_update=False), 'existing_comment': None}, True, False)]]
```

**Comment by jaschahuisman** [comment]
Same issue here... Can't seem to find the database and force reinstalling does not help. The only thing that helps is setting up another DB using `export LANGFLOW_DATABASE_URL=sqlite:///./langflow.db`

**Comment by anovazzi1** [comment]
Hello,
Sorry for the delay. Did you try using the new version? Does the error still persist?

**Comment by carlosrcoelho** [comment]
Hi @fcools 

We hope you're doing well. Just a friendly reminder that if we do not hear back from you within the next 3 days, we will close this issue. If you need more time or further assistance, please let us know. 

Thank you for your understanding!

**Comment by fcools** [comment]
Hi @carlosrcoelho,

Just did a clean install, Ubuntu 22.04 server, python 3.12.2, miniconda3 and LangFlow 1.0.10.
Everything works fine now, just a few depreciation errors, but running great with Ollama and llama3b.

Thanks for the excellent work!
