### ISSUE TITLE
Error when using Azure OpenAI model v1.0.0

### ISSUE THREAD

**Issue by JustTryAI** [langflow-ai/langflow#2333]
**Describe the bug**
Can't use the Basic Prompting (Hello, World) starter project with the Azure OpenAI model, I'm using the same settings that have worked with previous pre-release builds.
The error message I'm getting is:

Error Building Component
Error building Component Azure OpenAI: build_model not found in AzureChatOpenAIComponent

**Browser and Version**
Edge Version 126.0.2592.68 (Official build) (64-bit)

**To Reproduce**
1. Install v1.0.0
2. Delete OpenAI model 
3. Drag and Drop Azure OpenAI model
4. Select global variables
5. Press the play button on Azure OpenAI model

**Additional context**
Everything worked fine in 1.0.0a60, I have reinstalled a60 again to check that the variables I'm using are correct, and everything is working fine.
Unable to test in v1.0.3 as nothing seems to be working with this build for me, I have clean installed 1.0.3

**Comment by JustTryAI** [comment]
> Hello @JustTryAI! I'm here to help you with any bugs, questions, or contributions. Let's work together to solve the issue you're facing.
> 
> The error "build_model not found in AzureChatOpenAIComponent" occurs because the `AzureChatOpenAIComponent` class does not have a method named `build_model`. Instead, it has a method named `build`. To resolve this error, you should call the `build` method with the appropriate parameters.
> 
> Here is the relevant part of the `AzureChatOpenAIComponent` class:
> 
> ```python
> def build(
>     self,
>     model: str,
>     azure_endpoint: str,
>     azure_deployment: str,
>     api_key: str,
>     api_version: str,
>     temperature: float = 0.7,
>     max_tokens: Optional[int] = 1000,
> ) -> BaseLanguageModel:
>     try:
>         llm = AzureChatOpenAI(
>             model=model,
>             azure_endpoint=azure_endpoint,
>             azure_deployment=azure_deployment,
>             api_version=api_version,
>             api_key=api_key,
>             temperature=temperature,
>             max_tokens=max_tokens,
>         )
>     except Exception as e:
>         raise ValueError("Could not connect to AzureOpenAI API.") from e
>     return llm
> ```
> 
> Ensure that you are calling the `build` method instead of `build_model` [[1]](https://github.com/logspace-ai/langflow/blob/dev/src/backend/base/langflow/components/models/AzureOpenAIModel.py)[[2]](https://github.com/langflow-ai/langflow/blob/dev/src/backend/base/langflow/components/model_specs/AzureChatOpenAISpecs.py)[[3]](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/components/llms/AzureChatOpenAI.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I don't believe this response is correct as the Azure OpenAI model uses the "model_response" function instead of the build_model function used by other models.

**Comment by JustTryAI** [comment]
> Hello @JustTryAI! I'm here to help you with any bugs, questions, or contributions. Let's work together to solve the issue you're facing.
> 
> The error "build_model not found in AzureChatOpenAIComponent" occurs because the `AzureChatOpenAIComponent` class does not have a method named `build_model`. Instead, it has a method named `build`. To resolve this error, you should call the `build` method with the appropriate parameters.
> 
> Here is the relevant part of the `AzureChatOpenAIComponent` class:
> 
> ```python
> def build(
>     self,
>     model: str,
>     azure_endpoint: str,
>     azure_deployment: str,
>     api_key: str,
>     api_version: str,
>     temperature: float = 0.7,
>     max_tokens: Optional[int] = 1000,
> ) -> BaseLanguageModel:
>     try:
>         llm = AzureChatOpenAI(
>             model=model,
>             azure_endpoint=azure_endpoint,
>             azure_deployment=azure_deployment,
>             api_version=api_version,
>             api_key=api_key,
>             temperature=temperature,
>             max_tokens=max_tokens,
>         )
>     except Exception as e:
>         raise ValueError("Could not connect to AzureOpenAI API.") from e
>     return llm
> ```
> 
> Ensure that you are calling the `build` method instead of `build_model` [[1]](https://github.com/logspace-ai/langflow/blob/dev/src/backend/base/langflow/components/models/AzureOpenAIModel.py)[[2]](https://github.com/langflow-ai/langflow/blob/dev/src/backend/base/langflow/components/model_specs/AzureChatOpenAISpecs.py)[[3]](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/components/llms/AzureChatOpenAI.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

@dosu. I don't believe this response is correct as the Azure OpenAI model uses the "model_response" function instead of the build_model function used by other models.

**Comment by blucas-accela** [comment]
Same issue. Brand new install and same steps fail.

2024-06-26 09:56:30 - ERROR    - base - build_model not found in AzureChatOpenAIComponent                                                                                                                    base.py:627
                             Traceback (most recent call last):                                                                                                                                                                                      
                                                                                                                                                                                                                                                     
                               File "<frozen runpy>", line 198, in _run_module_as_main                                                                                                                                                               
                               File "<frozen runpy>", line 88, in _run_code   

Langflow v1.0.5
Python version = 3.12.3
OS = Mac Sonoma 14.4.1

**Comment by nikunjasahoo** [comment]
Tried Langflow for the first time for experimentation purpose and received the following error on building the AzureOpenAI Component.
AttributeError: build_model not found in AzureChatOpenAIComponent                        
ERROR    2024-06-27 09:03:02 - ERROR    -      service.py:76
                             service - Error stopping tracing                   
                             service: 'NoneType' object has no                  
                             attribute 'cancel' 

Verified all parameters are correctly configured.

Langflow v1.0.5
Python v3.12.1
MacOS Sonoma 14.5

**Comment by anantyash9** [comment]
I ran into the same issue.
changing the language model function at langflow/src/backend/base/langflow/components/models/AzureOpenAIModel.py fixed it. Rename the the run_model function to build_model to match all the other Language Models.  
`  outputs = [
        Output(display_name="Text", name="text_output", method="text_response"),
        Output(display_name="Language Model", name="model_output", method="build_model"),
    ]

    def build_model(self) -> LanguageModel:
        model = self.model
        azure_endpoint = self.azure_endpoint
        azure_deployment = self.azure_deployment
        api_version = self.api_version
        api_key = self.api_key
        temperature = self.temperature
        max_tokens = self.max_tokens
        stream = self.stream
`
install again and copy the static files of the frontend to the correct location wrt your install directory.
This seems to fix the issue.

**Comment by blucas-accela** [comment]
https://github.com/langflow-ai/langflow/pull/2339 has the fix in it
