### ISSUE TITLE
sqlite3.OperationalError: no such table: message

### ISSUE THREAD

**Issue by Nitewriter** [langflow-ai/langflow#2576]
When attempting to use `run_flow_from_json` with the Memory Chat example flow an sqlite3 error is produced.

```
sqlite3.OperationalError: no such table: message
```

**Browser and Version**
 - Browser N/A
 - Version 1.0.6

**To Reproduce**
1. Create a new flow using the `Memory Chat` template
2. Export the flow to JSON
3. Copy the `Python Code` example execution script from the `API` dialog
4. Execute the script to reproduce the error

**Traceback**
```
2024-07-08 09:06:05.390 | DEBUG    | langflow.services.manager:_create_service:61 - Create service ServiceType.DATABASE_SERVICE
2024-07-08 09:06:05.390 | DEBUG    | langflow.services.manager:_create_service:61 - Create service ServiceType.SETTINGS_SERVICE
2024-07-08 09:06:05.391 | DEBUG    | langflow.services.settings.base:set_database_url:175 - No database_url provided, trying LANGFLOW_DATABASE_URL env variable
2024-07-08 09:06:05.392 | DEBUG    | langflow.services.settings.base:set_database_url:180 - No database_url env variable, using sqlite database
2024-07-08 09:06:05.393 | DEBUG    | langflow.services.settings.base:set_database_url:199 - Saving database to langflow directory: /Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow
2024-07-08 09:06:05.393 | DEBUG    | langflow.services.settings.base:set_components_path:263 - Setting default components path to components_path
2024-07-08 09:06:05.393 | DEBUG    | langflow.services.settings.base:set_components_path:268 - Components path: ['/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/components']
2024-07-08 09:06:05.393 | DEBUG    | langflow.services.settings.base:set_user_agent:144 - Setting user agent to langflow
2024-07-08 09:06:05.394 | DEBUG    | langflow.services.settings.auth:get_secret_key:98 - No secret key provided, generating a random one
2024-07-08 09:06:05.395 | DEBUG    | langflow.services.settings.auth:get_secret_key:102 - Loaded secret key
2024-07-08 09:06:05.395 | DEBUG    | langflow.services.settings.auth:validate_superuser:76 - Resetting superuser password to default value
Traceback (most recent call last):
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 402, in run
    loop = asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/vertex/base.py", line 618, in _get_and_instantiate_class
    result = await loading.instantiate_class(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/interface/initialize/loading.py", line 39, in instantiate_class
    custom_component, build_results, artifacts = await build_component_and_get_results(
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/interface/initialize/loading.py", line 72, in build_component_and_get_results
    return await build_component(params=params_copy, custom_component=custom_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/interface/initialize/loading.py", line 146, in build_component
    build_results, artifacts = await custom_component.build_results()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/custom/custom_component/component.py", line 136, in build_results
    return await self._build_with_tracing()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/custom/custom_component/component.py", line 125, in _build_with_tracing
    _results, _artifacts = await self._build_results()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/custom/custom_component/component.py", line 154, in _build_results
    result = method()
             ^^^^^^^^
  File "<string>", line 85, in retrieve_messages_as_text
  File "<string>", line 74, in retrieve_messages
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/memory.py", line 57, in get_messages
    messages = session.exec(stmt)
               ^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlmodel/orm/session.py", line 68, in exec
    results = super().execute(
              ^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2351, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2236, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: message
[SQL: SELECT message.timestamp, message.sender, message.sender_name, message.session_id, message.text, message.id, message.flow_id, message.files 
FROM message ORDER BY message.timestamp ASC
 LIMIT ? OFFSET ?]
[parameters: (100, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 341, in _run
    await self.process(start_component_id=start_component_id, fallback_to_env_vars=fallback_to_env_vars)
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 964, in process
    raise e
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 961, in process
    next_runnable_vertices = await self._execute_tasks(tasks, lock=lock)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 986, in _execute_tasks
    raise result
  File "/Users/nitewriter/.pyenv/versions/3.11.9/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 898, in build_vertex
    raise exc
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 878, in build_vertex
    await vertex.build(
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/vertex/base.py", line 713, in build
    await step(user_id=user_id, **kwargs)
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/vertex/base.py", line 414, in _build
    await self._get_and_instantiate_class(user_id, fallback_to_env_vars)
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/vertex/base.py", line 628, in _get_and_instantiate_class
    raise ComponentBuildException(f"Error building Component {self.display_name}:\n\n{exc}", tb) from exc
langflow.exceptions.component.ComponentBuildException: Error building Component Chat Memory:

(sqlite3.OperationalError) no such table: message
[SQL: SELECT message.timestamp, message.sender, message.sender_name, message.session_id, message.text, message.id, message.flow_id, message.files 
FROM message ORDER BY message.timestamp ASC
 LIMIT ? OFFSET ?]
[parameters: (100, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/runtime/__main__.py", line 30, in <module>
    main()
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/runtime/__main__.py", line 19, in main
    result = run_flow_from_json(
             ^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/load/load.py", line 126, in run_flow_from_json
    result = run_graph(
             ^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/processing/process.py", line 102, in run_graph
    run_outputs = graph.run(
                  ^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 407, in run
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/Users/nitewriter/.pyenv/versions/3.11.9/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Users/nitewriter/.pyenv/versions/3.11.9/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 455, in arun
    run_outputs = await self._run(
                  ^^^^^^^^^^^^^^^^
  File "/Volumes/WillowTreeCS/WillowTree/dart-langflow-runtime/.venv/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 347, in _run
    raise ValueError(f"Error running graph: {exc}") from exc
ValueError: Error running graph: Error building Component Chat Memory:

(sqlite3.OperationalError) no such table: message
[SQL: SELECT message.timestamp, message.sender, message.sender_name, message.session_id, message.text, message.id, message.flow_id, message.files 
FROM message ORDER BY message.timestamp ASC
 LIMIT ? OFFSET ?]
[parameters: (100, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
(.venv)
```

**Comment by Nitewriter** [comment]
@dosu Almost a functional workaround. You missed two columns:

```
        flow_id TEXT,
        files LIST,
```

**Comment by Nitewriter** [comment]
Ahh, I made a discovery. `nest-asyncio` is required for the database tables to be automatically created. Installing this package fixed the issue I was hitting.

**Comment by lvergergsk** [comment]
FYI
I got same error.
In my case, I just forgot to update poetry lock file.
