### ISSUE TITLE
Component has not been built yet

### ISSUE THREAD

**Issue by zdql** [langflow-ai/langflow#2656]
**Describe the bug**

We run langflow via a pip install in a docker file, passing in 4 celery workers like so: 

```
FROM python:3.10-slim

COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

RUN pip install langflow==1.0.8 -U --user

COPY custom_components /app/custom_components

CMD ["python", "-m", "langflow", "run", "--host", "0.0.0.0", "--port", "7860", "--components-path", "/app/custom_components", "--workers", "4"]
```

**Browser and Version**
 - Browser - Bug occurs n Safari or Chrome
 - Version - We've seen it since 1.0.5, we're currently running on 1.0.8

**To Reproduce**
Host langflow with our docker file and attempt to run any flow. The error will happen sporadically when running flows 

This is the stack trace we see: 

```
Component Text Input has not been built yet

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/langflow/api/v1/chat.py", line 198, in build_vertex
    ) = await graph.build_vertex(
  File "/root/.local/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 913, in build_vertex
    raise exc
  File "/root/.local/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 893, in build_vertex
    await vertex.build(
  File "/root/.local/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 721, in build
    await step(user_id=user_id, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 421, in _build
    await self._build_each_vertex_in_params_dict(user_id)
  File "/root/.local/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 484, in _build_each_vertex_in_params_dict
    await self._build_vertex_and_update_params(
  File "/root/.local/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 560, in _build_vertex_and_update_params
    result = await vertex.get_result(self)
  File "/root/.local/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 535, in get_result
    return await self._get_result(requester)
  File "/root/.local/lib/python3.10/site-packages/langflow/graph/vertex/types.py", line 84, in _get_result
    raise ValueError(f"Component {self.display_name} has not been built yet")
ValueError: Component Text Input has not been built yet
```

**Additional context**
We've seen this occur on both our custom components and the langflow built in components. The error happens about 40% of the time when running a flow.

**Comment by carlosrcoelho** [comment]
Hey @zdql 

Have you tried the latest version? We've improved the way errors are presented to the user.

**Comment by jordanrfrazier** [comment]
Hi @zdql apologies for the late response here. I created a docker image using:
```
FROM python:3.10-slim

RUN pip install langflow -U --user
# on v1.0.18

CMD ["python", "-m", "langflow", "run", "--host", "0.0.0.0", "--port", "7860", "--workers", "4"]
```
and created the Basic Prompting and ran it multiple times with no issue. It's possible that a more complex flow results in this issue. (I don't suspect your custom component causes an issue, due to the error pointing to the Chat Input). 

And I may be misunderstanding your setup - the `--workers` argument in the `langflow run` command sets the number of uvicorn processes: https://github.com/langflow-ai/langflow/blob/main/src/backend/base/langflow/main.py#L248

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
