### ISSUE TITLE
Access token not being updated

### ISSUE THREAD

**Issue by anovazzi1** [langflow-ai/langflow#2787]
### Bug Description

after some logging I notice that somehow the refresh endpoint is returning the same access token that is invalid, making the user to log out.

### Reproduction

After leaving Langflow idle for a while, the access token became invalid, causing an error that does not occur consistently.

Function that refresh the token, notice that i add some logging to the LocalStorage to track the bug.

```
  async function tryToRenewAccessToken(error: AxiosError) {
    try {
      if (window.location.pathname.includes("/login")) return;
      const res = await renewAccessToken();
      window.localStorage.setItem("renewAccess-"+ (new Date(Date.now())).toLocaleString(), JSON.stringify({error:error,res: res,oldAccess:accessToken}));
      if (res?.data?.access_token && res?.data?.refresh_token) {
        login(res?.data?.access_token);
      }
    } catch (error) {
      window.localStorage.setItem("renewAccessError-"+ (new Date(Date.now())).toLocaleString(), JSON.stringify({error,oldAccess:accessToken}));
      clearBuildVerticesState(error);
      logout();
      return Promise.reject("Authentication error");
    }
  }
  ```
raw log:
  ```
  "renewAccess-7/17/2024, 5:46:08 PM": "{\"error\":{\"message\":\"Request failed with status code 401\",\"name\":\"AxiosError\",\"stack\":\"AxiosError: Request failed with status code 401\\n    at settle (http://192.168.112.119/assets/index-wbBkQbfc.js:1030:1239)\\n    at XMLHttpRequest.st (http://192.168.112.119/assets/index-wbBkQbfc.js:1030:6870)\",\"config\":{\"transitional\":{\"silentJSONParsing\":true,\"forcedJSONParsing\":true,\"clarifyTimeoutError\":false},\"adapter\":[\"xhr\",\"http\",\"fetch\"],\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1,\"env\":{},\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Authorization\":\"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMWZkYzgxNy1lNjNiLTRmYjMtYWUyZS1lN2NlMGQzMTZhMDMiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMjUyNzY4fQ.lRVg0dW-KHUkzeqk_P6nwEHcbwGDpZZOEjNs2o1vrJY\"},\"baseURL\":\"\",\"method\":\"get\",\"url\":\"/api/v1/users/whoami\",\"signal\":{}},\"code\":\"ERR_BAD_REQUEST\",\"status\":401},\"res\":{\"data\":{\"access_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMWZkYzgxNy1lNjNiLTRmYjMtYWUyZS1lN2NlMGQzMTZhMDMiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMjUyNzY4fQ.lRVg0dW-KHUkzeqk_P6nwEHcbwGDpZZOEjNs2o1vrJY\",\"refresh_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMWZkYzgxNy1lNjNiLTRmYjMtYWUyZS1lN2NlMGQzMTZhMDMiLCJ0eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyMTg1Mzk2OH0.-G-pOMWYLxdN-j7ujU0tKcdyV6ZdUszZAv4xO5ljhQw\",\"token_type\":\"bearer\"},\"status\":200,\"statusText\":\"OK\",\"headers\":{\"access-control-allow-credentials\":\"true\",\"access-control-allow-origin\":\"http://192.168.112.119\",\"content-length\":\"435\",\"content-type\":\"application/json\",\"date\":\"Wed, 17 Jul 2024 20:46:07 GMT\",\"server\":\"uvicorn\",\"timing-allow-origin\":\"*\",\"vary\":\"Origin\"},\"config\":{\"transitional\":{\"silentJSONParsing\":true,\"forcedJSONParsing\":true,\"clarifyTimeoutError\":false},\"adapter\":[\"xhr\",\"http\",\"fetch\"],\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":0,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1,\"env\":{},\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"Content-Type\":\"application/x-www-form-urlencoded\",\"Authorization\":\"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMWZkYzgxNy1lNjNiLTRmYjMtYWUyZS1lN2NlMGQzMTZhMDMiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMjUyNzY4fQ.lRVg0dW-KHUkzeqk_P6nwEHcbwGDpZZOEjNs2o1vrJY\"},\"baseURL\":\"\",\"method\":\"post\",\"url\":\"/api/v1/refresh\",\"signal\":{}},\"request\":{\"jamTraceId\":\"jam-trace-7460.78380764060391831721249168092\"}},\"oldAccess\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMWZkYzgxNy1lNjNiLTRmYjMtYWUyZS1lN2NlMGQzMTZhMDMiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMjUyNzY4fQ.lRVg0dW-KHUkzeqk_P6nwEHcbwGDpZZOEjNs2o1vrJY\"}",
  ```
  parsed with gpt:
  ```
  const data = {
  "renewAccess-7/17/2024, 5:46:08 PM": {
    "error": {
      "message": "Request failed with status code 401",
      "name": "AxiosError",
      "stack": "AxiosError: Request failed with status code 401\n    at settle (http://192.168.112.119/assets/index-wbBkQbfc.js:1030:1239)\n    at XMLHttpRequest.st (http://192.168.112.119/assets/index-wbBkQbfc.js:1030:6870)",
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": ["xhr", "http", "fetch"],
        "transformRequest": [null],
        "transformResponse": [null],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMWZkYzgxNy1lNjNiLTRmYjMtYWUyZS1lN2NlMGQzMTZhMDMiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMjUyNzY4fQ.lRVg0dW-KHUkzeqk_P6nwEHcbwGDpZZOEjNs2o1vrJY"
        },
        "baseURL": "",
        "method": "get",
        "url": "/api/v1/users/whoami",
        "signal": {}
      },
      "code": "ERR_BAD_REQUEST",
      "status": 401
    },
    "res": {
      "data": {
        "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMWZkYzgxNy1lNjNiLTRmYjMtYWUyZS1lN2NlMGQzMTZhMDMiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMjUyNzY4fQ.lRVg0dW-KHUkzeqk_P6nwEHcbwGDpZZOEjNs2o1vrJY",
        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMWZkYzgxNy1lNjNiLTRmYjMtYWUyZS1lN2NlMGQzMTZhMDMiLCJ0eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyMTg1Mzk2OH0.-G-pOMWYLxdN-j7ujU0tKcdyV6ZdUszZAv4xO5ljhQw",
        "token_type": "bearer"
      },
      "status": 200,
      "statusText": "OK",
      "headers": {
        "access-control-allow-credentials": "true",
        "access-control-allow-origin": "http://192.168.112.119",
        "content-length": "435",
        "content-type": "application/json",
        "date": "Wed, 17 Jul 2024 20:46:07 GMT",
        "server": "uvicorn",
        "timing-allow-origin": "*",
        "vary": "Origin"
      },
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": ["xhr", "http", "fetch"],
        "transformRequest": [null],
        "transformResponse": [null],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Content-Type": "application/x-www-form-urlencoded",
          "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMWZkYzgxNy1lNjNiLTRmYjMtYWUyZS1lN2NlMGQzMTZhMDMiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMjUyNzY4fQ.lRVg0dW-KHUkzeqk_P6nwEHcbwGDpZZOEjNs2o1vrJY"
        },
        "baseURL": "",
        "method": "post",
        "url": "/api/v1/refresh",
        "signal": {}
      },
      "request": {
        "jamTraceId": "jam-trace-7460.78380764060391831721249168092"
      }
    },
    "oldAccess": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMWZkYzgxNy1lNjNiLTRmYjMtYWUyZS1lN2NlMGQzMTZhMDMiLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIxMjUyNzY4fQ.lRVg0dW-KHUkzeqk_P6nwEHcbwGDpZZOEjNs2o1vrJY"
  }
};
```
  

### Expected behavior

Expected that the user was not logout suddenly. 

### Who can help?

@Cristhianzl

### Operating System

Ubuntu Linux 22.04

### Langflow Version

1.0.10

### Python Version

- [ ] 3.12
- [ ] 3.11
- [X] 3.10

**Comment by Cristhianzl** [comment]
on it.
