### ISSUE TITLE
Can't locate revision identified by xxx

### ISSUE THREAD

**Issue by artemus717** [langflow-ai/langflow#2905]
### Bug Description

╭───────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                             │
│                                                   │
│ Access http://0.0.0.0:7860                        │
│ Collaborate, and contribute at our GitHub Repo 🚀 │
╰───────────────────────────────────────────────────╯
[2024-07-24 03:11:41 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2024-07-24 03:11:41 +0000] [1] [INFO] Listening at: http://0.0.0.0:7860 (1)
[2024-07-24 03:11:41 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-07-24 03:11:41 +0000] [31] [INFO] Booting worker with pid: 31
[2024-07-24 03:11:41 +0000] [31] [INFO] Started server process [31]
[2024-07-24 03:11:41 +0000] [31] [INFO] Waiting for application startup.
[07/24/24 03:11:41] INFO     2024-07-24 03:11:41 - INFO     -     service.py:142
                             service - Alembic already
                             initialized
                    INFO     2024-07-24 03:11:41 - INFO     -     service.py:150
                             service - Running DB migrations in
                             /home/user/.local/lib/python3.10/sit
                             e-packages/langflow/alembic
                    WARNING  2024-07-24 03:11:41 - WARNING  - utils  utils.py:43
                             - Wrong revision in DB, deleting
                             alembic_version table and running
                             migrations again
                    INFO     2024-07-24 03:11:41 - INFO     -     service.py:142
                             service - Alembic already
                             initialized
                    INFO     2024-07-24 03:11:41 - INFO     -     service.py:150
                             service - Running DB migrations in
                             /home/user/.local/lib/python3.10/sit
                             e-packages/langflow/alembic
                    ERROR    2024-07-24 03:11:41 - ERROR    - utils utils.py:216
                             - Can't locate revision identified by
                             'bc804d8e7a18'
[2024-07-24 03:11:41 +0000] [31] [ERROR] Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 251, in _catch_revision_errors
    yield
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 314, in get_revisions
    self.revision_map.get_revisions(id_),
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 566, in get_revisions
    return tuple(
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 567, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 638, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch 'bc804d8e7a18'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/database/service.py", line 153, in run_migrations
    command.check(alembic_cfg)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/command.py", line 290, in check
    script_directory.run_env()
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/user/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/.local/lib/python3.10/site-packages/langflow/alembic/env.py", line 88, in <module>
    run_migrations_online()
  File "/home/user/.local/lib/python3.10/site-packages/langflow/alembic/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/user/.local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 615, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/user/.local/lib/python3.10/site-packages/alembic/command.py", line 279, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 570, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 588, in _run_environment
    if set(self.script_directory.get_revisions(rev)) != set(
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 311, in get_revisions
    with self._catch_revision_errors():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 283, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by 'bc804d8e7a18'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 251, in _catch_revision_errors
    yield
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 459, in _upgrade_revs
    for script in reversed(list(revs))
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 813, in iterate_revisions
    revisions, heads = fn(
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 1466, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 566, in get_revisions
    return tuple(
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 567, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 638, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch 'bc804d8e7a18'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/database/utils.py", line 32, in initialize_database
    database_service.run_migrations(fix=fix_migration)
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/database/service.py", line 156, in run_migrations
    command.upgrade(alembic_cfg, "head")
  File "/home/user/.local/lib/python3.10/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/user/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/.local/lib/python3.10/site-packages/langflow/alembic/env.py", line 88, in <module>
    run_migrations_online()
  File "/home/user/.local/lib/python3.10/site-packages/langflow/alembic/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/user/.local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 615, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/user/.local/lib/python3.10/site-packages/alembic/command.py", line 392, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 447, in _upgrade_revs
    with self._catch_revision_errors(
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 283, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by 'bc804d8e7a18'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 251, in _catch_revision_errors
    yield
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 314, in get_revisions
    self.revision_map.get_revisions(id_),
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 566, in get_revisions
    return tuple(
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 567, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 638, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch 'bc804d8e7a18'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/database/service.py", line 153, in run_migrations
    command.check(alembic_cfg)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/command.py", line 290, in check
    script_directory.run_env()
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/user/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/.local/lib/python3.10/site-packages/langflow/alembic/env.py", line 88, in <module>
    run_migrations_online()
  File "/home/user/.local/lib/python3.10/site-packages/langflow/alembic/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/user/.local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 615, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/user/.local/lib/python3.10/site-packages/alembic/command.py", line 279, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 570, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/autogenerate/api.py", line 588, in _run_environment
    if set(self.script_directory.get_revisions(rev)) != set(
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 311, in get_revisions
    with self._catch_revision_errors():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 283, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by 'bc804d8e7a18'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 251, in _catch_revision_errors
    yield
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 459, in _upgrade_revs
    for script in reversed(list(revs))
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 813, in iterate_revisions
    revisions, heads = fn(
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 1466, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 543, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 566, in get_revisions
    return tuple(
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 567, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/revision.py", line 638, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch 'bc804d8e7a18'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/user/.local/lib/python3.10/site-packages/langflow/main.py", line 20, in lifespan
    initialize_services()
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/utils.py", line 217, in initialize_services
    raise exc
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/utils.py", line 214, in initialize_services
    initialize_database(fix_migration=fix_migration)
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/database/utils.py", line 46, in initialize_database
    database_service.run_migrations(fix=fix_migration)
  File "/home/user/.local/lib/python3.10/site-packages/langflow/services/database/service.py", line 156, in run_migrations
    command.upgrade(alembic_cfg, "head")
  File "/home/user/.local/lib/python3.10/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/user/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/.local/lib/python3.10/site-packages/langflow/alembic/env.py", line 88, in <module>
    run_migrations_online()
  File "/home/user/.local/lib/python3.10/site-packages/langflow/alembic/env.py", line 82, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/user/.local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 615, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/user/.local/lib/python3.10/site-packages/alembic/command.py", line 392, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 447, in _upgrade_revs
    with self._catch_revision_errors(
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/.local/lib/python3.10/site-packages/alembic/script/base.py", line 283, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by 'bc804d8e7a18'
[2024-07-24 03:11:41 +0000] [31] [ERROR] Application startup failed. Exiting.
[2024-07-24 03:11:41 +0000] [31] [INFO] Worker exiting (pid: 31)
[2024-07-24 03:11:42 +0000] [1] [ERROR] Worker (pid:31) exited with code 3
[2024-07-24 03:11:42 +0000] [1] [ERROR] Shutting down: Master
[2024-07-24 03:11:42 +0000] [1] [ERROR] Reason: Worker failed to boot.

### Reproduction

Upgrade from 0.6.10 to 1.0.12 went wrong.
And I tried langflow migration --fix , but still this error

### Expected behavior

Startup correctly.

### Operating System

Docker Image

### Langflow Version

1.0.12

### Python Version

None

**Comment by artemus717** [comment]
how can I fix this when I am using docker image

**Comment by carlosrcoelho** [comment]
Hey @artemus717 

Hey, could you try using the new version and let me know if the issue is still there? Thanks!

**Comment by artemus717** [comment]
Hi @carlosrcoelho  This issue disappeared. Thanks.
But there are still other error caused upgrade from 0.6.16 to 1.0.14 failed. I report that error in other issue.
