### ISSUE TITLE
Run Flow crashes

### ISSUE THREAD

**Issue by Gluepower** [langflow-ai/langflow#3184]
### Bug Description

Using Langflow version 1.0.14 on Render

When trying to use Run Flow, it give error Error building Component Run Flow: 

Error building Component Run Flow: 

'in <string>' requires string as left operand, not NoneType

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 658, in _build_results
    result = await loading.get_instance_results(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 60, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 147, in build_component
    build_results, artifacts = await custom_component.build_results()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 120, in build_results
    return await self._build_with_tracing()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 110, in _build_with_tracing
    _results, _artifacts = await self._build_results()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 141, in _build_results
    result = await result
             ^^^^^^^^^^^^
  File "<string>", line 51, in generate_results
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/custom_component.py", line 486, in run_flow
    return await run_flow(
           ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/helpers/flow.py", line 98, in run_flow
    vertex.is_output and (output_type == "any" or output_type in vertex.id.lower())  # type: ignore
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'in <string>' requires string as left operand, not NoneType
![image](https://github.com/user-attachments/assets/e4100d22-fba0-4982-a3bf-3b47e49746c3)

### Reproduction

1. add chat input component
2. add Run flow
3. Select any flow in the component to be run
4. go to playground and type something

### Expected behavior

the flow in component should be called and executed

### Operating System

Render

### Langflow Version

1.0.14

### Python Version

3.12

### Flow File

[Basic Prompting (Hello, World) (1).json](https://github.com/user-attachments/files/16478976/Basic.Prompting.Hello.World.1.json)

**Comment by lucaseduoli** [comment]
The issue is already resolved and the version that fixes it is going to be released today. Thanks for the feedback!
