### ISSUE TITLE
Error building Component Run Flow:

### ISSUE THREAD

**Issue by diegomustafamarino** [langflow-ai/langflow#3217]
### Bug Description

Component Run Flow is not working.

### Reproduction

connect any input to Run Flow component.
In this case i tried with a simple chat input and chat output.
ps: Flow as Tool and Sub Flow is not working too.

### Expected behavior

I expected it could run a flow and output the data, using the same session of the main flow.
I continued with curl, but i didn't like the delay.

### Operating System

ubuntu

### Langflow Version

1.0.14

### Python Version

None

### Screenshot

Error building Component Run Flow: 

'in <string>' requires string as left operand, not NoneType

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 658, in _build_results
    result = await loading.get_instance_results(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 60, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 147, in build_component
    build_results, artifacts = await custom_component.build_results()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 140, in build_results
    return await self._build_with_tracing()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 130, in _build_with_tracing
    _results, _artifacts = await self._build_results()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 161, in _build_results
    result = await result
             ^^^^^^^^^^^^
  File "<string>", line 56, in generate_results
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/custom_component.py", line 486, in run_flow
    return await run_flow(
           ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/helpers/flow.py", line 98, in run_flow
    vertex.is_output and (output_type == "any" or output_type in vertex.id.lower())  # type: ignore
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by vasconceloscezar** [comment]
Run Flow is still in Experimental, so I suggest you not rely too much on those components. 

With that said, I think you can try the `Sub Flow` component, it seems to be a bit more stable for me in my tests

**Comment by lucaseduoli** [comment]
Hello! The Run Flow and Sub Flow components are supposed to be working now in the last version of main. The next release is coming shortly to push those changes to the pip-installable version! Thanks for the feedback.
