### ISSUE TITLE
Streaming in 1.0.16 error: All of session_id, sender, and sender_name must be provided.

### ISSUE THREAD

**Issue by hakan-77** [langflow-ai/langflow#3515]
### Bug Description

Error on Streaming
All of session_id, sender, and sender_name must be provided.

### Reproduction

1- Turn on streaming 
2- open chat window, test

everything will work but on each try the user will get an error message.

### Expected behavior

No error message

### Operating System

MacOS

### Langflow Version

1.0.16

### Python Version

None

### Screenshot

Trace

                                                                                                                           
                             ╭──────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────╮            
                             │ /Users/...../venv/...............-langflow/lib/python3.10/site-packages/langflow/api/v1/chat.py:665 in     │            
                             │ stream_vertex                                                                                              │            
                             │                                                                                                            │            
                             │   662 │   │   │   │   │   │   data={"message": f"Streaming vertex {vertex_id}"},                           │            
                             │   663 │   │   │   │   │   )                                                                                │            
                             │   664 │   │   │   │   │   yield str(stream_data)                                                           │            
                             │ ❱ 665 │   │   │   │   │   async for chunk in vertex.stream():                                              │            
                             │   666 │   │   │   │   │   │   stream_data = StreamData(                                                    │            
                             │   667 │   │   │   │   │   │   │   event="message",                                                         │            
                             │   668 │   │   │   │   │   │   │   data={"chunk": chunk},                                                   │            
                             │                                                                                                            │            
                             │ /Users/...../venv/...............-langflow/lib/python3.10/site-packages/langflow/graph/vertex/types.py:429 │            
                             │ in stream                                                                                                  │            
                             │                                                                                                            │            
                             │   426 │   │   │   if hasattr(self._custom_component, "should_store_message") and hasattr(                  │            
                             │   427 │   │   │   │   self._custom_component, "store_message"                                              │            
                             │   428 │   │   │   ):                                                                                       │            
                             │ ❱ 429 │   │   │   │   self._custom_component.store_message(message)                                        │            
                             │   430 │   │   log_vertex_build(                                                                            │            
                             │   431 │   │   │   flow_id=self.graph.flow_id,                                                              │            
                             │   432 │   │   │   vertex_id=self.id,                                                                       │            
                             │                                                                                                            │            
                             │ /Users/...../venv/...............-langflow/lib/python3.10/site-packages/langflow/base/io/chat.py:58 in     │            
                             │ store_message                                                                                              │            
                             │                                                                                                            │            
                             │   55 │   │   self,                                                                                         │            
                             │   56 │   │   message: Message,                                                                             │            
                             │   57 │   ) -> list[Message]:                                                                               │            
                             │ ❱ 58 │   │   messages = store_message(                                                                     │            
                             │   59 │   │   │   message,                                                                                  │            
                             │   60 │   │   │   flow_id=self.graph.flow_id,                                                               │            
                             │   61 │   │   )                                                                                             │            
                             │                                                                                                            │            
                             │ /Users/...../venv/...............-langflow/lib/python3.10/site-packages/langflow/memory.py:136 in          │            
                             │ store_message                                                                                              │            
                             │                                                                                                            │            
                             │   133 │   │   return []                                                                                    │            
                             │   134 │                                                                                                    │            
                             │   135 │   if not message.session_id or not message.sender or not message.sender_name:                      │            
                             │ ❱ 136 │   │   raise ValueError("All of session_id, sender, and sender_name must be provided.")             │            
                             │   137 │                                                                                                    │            
                             │   138 │   return add_messages([message], flow_id=flow_id)                                                  │            
                             │   139                                                                                                      │            
                             ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by carlosrcoelho** [comment]
@hakan-77 

the fix is already merged. Feel free to give it a try. Let me know if there's any issue.

**Comment by hakan-77** [comment]
@carlosrcoelho evertyhing works. Thanks.

**Comment by roots-ai** [comment]
Using Langflow 1.1

Still gets this error in JSON parser in a sub-flow.

While the sub-flow independently works without any errors.


```
Error building Component Fields: 

Error running graph: Error building Component Active Domains JSON: 

All of session_id, sender, and sender_name must be provided.

Traceback (most recent call last):
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 837, in build_results
    return await self._build_with_tracing()
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 819, in _build_with_tracing
    _results, _artifacts = await self._build_results()
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 885, in _build_results
    result = await asyncio.to_thread(method)
  File "/usr/local/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/local/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<string>", line 74, in clean_json
ValueError: Invalid JSON string: Missing '{' or '}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 708, in _build_results
    result = await initialize.loading.get_instance_results(
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/interface/initialize/loading.py", line 68, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/interface/initialize/loading.py", line 145, in build_component
    build_results, artifacts = await custom_component.build_results()
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 848, in build_results
    self.send_error(
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 1135, in send_error
    self.send_message(error_message)
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 1009, in send_message
    stored_message = self._store_message(message)
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 1034, in _store_message
    messages = store_message(message, flow_id=flow_id)
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/memory.py", line 167, in store_message
    raise ValueError(msg)
ValueError: All of session_id, sender, and sender_name must be provided.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 771, in _run
    await self.process(start_component_id=start_component_id, fallback_to_env_vars=fallback_to_env_vars)
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 1518, in process
    next_runnable_vertices = await self._execute_tasks(tasks, lock=lock)
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 1570, in _execute_tasks
    raise result
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 1419, in build_vertex
    await vertex.build(
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 818, in build
    await step(user_id=user_id, event_manager=event_manager, **kwargs)
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 496, in _build
    await self._build_results(
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 723, in _build_results
    raise ComponentBuildError(msg, tb) from exc
langflow.exceptions.component.ComponentBuildError: Error building Component Active Domains JSON: 

All of session_id, sender, and sender_name must be provided.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 708, in _build_results
    result = await initialize.loading.get_instance_results(
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/interface/initialize/loading.py", line 68, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/interface/initialize/loading.py", line 145, in build_component
    build_results, artifacts = await custom_component.build_results()
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 837, in build_results
    return await self._build_with_tracing()
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 819, in _build_with_tracing
    _results, _artifacts = await self._build_results()
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 883, in _build_results
    result = await method()
  File "<string>", line 101, in generate_results
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/custom/custom_component/custom_component.py", line 490, in run_flow
    return await run_flow(
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/helpers/flow.py", line 123, in run_flow
    return await graph.arun(
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 840, in arun
    run_outputs = await self._run(
  File "/.local/pipx/venvs/langflow/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 776, in _run
    raise ValueError(msg) from exc
ValueError: Error running graph: Error building Component Active Domains JSON: 

All of session_id, sender, and sender_name must be provided.
``

**Comment by roots-ai** [comment]
Any updates here? The issue keeps on happening when using sub-flows.

**Comment by AQK99** [comment]
@carlosrcoelho
I'm having the same issue when using sub-flows. can we get an update please?
