### ISSUE TITLE
Running  langflow on local does not work . Deprecated method used in code 

### ISSUE THREAD

**Issue by pulkit21aug** [langflow-ai/langflow#3543]
### Bug Description

Langflow can no start and fails with error 
```
C:\Users\Aarav Saxena>langflow run
C:\python\lib\site-packages\langchain\_api\module_import.py:120: LangChainDeprecationWarning: Importing SQLDatabase from langchain is deprecated. Please replace deprecated imports:

>> from langchain import SQLDatabase

with new imports of:

>> from langchain_community.utilities import SQLDatabase

  warn_deprecated(
C:\python\lib\site-packages\langchain\_api\module_import.py:120: LangChainDeprecationWarning: Importing RequestsWrapper from langchain is deprecated. Please replace deprecated imports:

>> from langchain import RequestsWrapper

with new imports of:

>> from langchain_community.utilities import RequestsWrapper

  warn_deprecated(
Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\python\Scripts\langflow.exe\__main__.py", line 4, in <module>
    from langflow.__main__ import main
  File "C:\python\lib\site-packages\langflow\__main__.py", line 17, in <module>
    from langflow.main import setup_app
  File "C:\python\lib\site-packages\langflow\main.py", line 11, in <module>
    from langflow.api import router
  File "C:\python\lib\site-packages\langflow\api\__init__.py", line 1, in <module>
    from langflow.api.router import router
  File "C:\python\lib\site-packages\langflow\api\router.py", line 4, in <module>
    from langflow.api.v1 import (
  File "C:\python\lib\site-packages\langflow\api\v1\__init__.py", line 1, in <module>
    from langflow.api.v1.api_key import router as api_key_router
  File "C:\python\lib\site-packages\langflow\api\v1\api_key.py", line 8, in <module>
    from langflow.services.auth import utils as auth_utils
  File "C:\python\lib\site-packages\langflow\services\auth\utils.py", line 5, in <module>
    from cryptography.fernet import Fernet
  File "C:\python\lib\site-packages\cryptography\fernet.py", line 14, in <module>
    from cryptography.exceptions import InvalidSignature
  **File "C:\python\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.**

C:\Users\Aarav Saxena>
```
### Reproduction

1. install langflow pip install langflow
2.  langflow run

### Expected behavior

langflow UI should launch successfully 

### Operating System

Windows 11

### Langflow Version

0.6.19

### Python Version

3.10

**Comment by carlosrcoelho** [comment]
@pulkit21aug 

Try to update Langflow with this command:
`python -m pip install langflow -U`

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to assist you.
