### ISSUE TITLE
unhashable type: 'Output'

### ISSUE THREAD

**Issue by severfire** [langflow-ai/langflow#3647]
### Bug Description

I am getting error while trying to build component that is getting data from my custom component. 

unhashable type: 'Output'

```
Traceback (most recent call last):
  File "/home/arek/.local/pipx/venvs/langflow/lib/python3.11/site-packages/langflow/api/v1/chat.py", line 218, in _build_vertex
    vertex_build_result = await graph.build_vertex(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arek/.local/pipx/venvs/langflow/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 1306, in build_vertex
    raise exc
  File "/home/arek/.local/pipx/venvs/langflow/lib/python3.11/site-packages/langflow/graph/graph/base.py", line 1276, in build_vertex
    await vertex.build(
  File "/home/arek/.local/pipx/venvs/langflow/lib/python3.11/site-packages/langflow/graph/vertex/base.py", line 792, in build
    await step(user_id=user_id, **kwargs)
  File "/home/arek/.local/pipx/venvs/langflow/lib/python3.11/site-packages/langflow/graph/vertex/base.py", line 464, in _build
    await self._build_each_vertex_in_params_dict(user_id)
  File "/home/arek/.local/pipx/venvs/langflow/lib/python3.11/site-packages/langflow/graph/vertex/base.py", line 551, in _build_each_vertex_in_params_dict
    await self._build_vertex_and_update_params(
  File "/home/arek/.local/pipx/venvs/langflow/lib/python3.11/site-packages/langflow/graph/vertex/base.py", line 629, in _build_vertex_and_update_params
    result = await vertex.get_result(self, target_handle_name=key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arek/.local/pipx/venvs/langflow/lib/python3.11/site-packages/langflow/graph/vertex/base.py", line 602, in get_result
    return await self._get_result(requester, target_handle_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arek/.local/pipx/venvs/langflow/lib/python3.11/site-packages/langflow/graph/vertex/types.py", line 124, in _get_result
    output = self.get_output(edge.source_handle.name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arek/.local/pipx/venvs/langflow/lib/python3.11/site-packages/langflow/graph/vertex/types.py", line 48, in get_output
    return self._custom_component.get_output(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 69, in get_output
TypeError: unhashable type: 'Output'
```

my custom component, which was  working on previous version of langflow:

```
import json
from typing import Dict, Any, Optional
from langflow.custom import Component
from langflow.inputs import MessageTextInput
from langflow.template import Output
from langflow.schema.message import Message

class JsonSplitter(Component):
    display_name = "JSON Splitter"
    description = "Splits JSON objects into separate outputs based on specified keys"
    icon = "splitCells"
    name = "JsonSplitter"

    inputs = [
        MessageTextInput(
            name="json_input",
            display_name="JSON Input",
            info="JSON string to be split",
        ),
        MessageTextInput(
            name="key_1",
            display_name="Key 1",
            info="First key to extract from JSON",
        ),
        MessageTextInput(
            name="key_2",
            display_name="Key 2",
            info="Second key to extract from JSON",
        ),
        MessageTextInput(
            name="key_3",
            display_name="Key 3",
            info="Third key to extract from JSON",
        ),
        MessageTextInput(
            name="key_4",
            display_name="Key 4",
            info="Third key to extract from JSON",
        ),
    ]

    outputs = [
        Output(display_name="Output 1", name="output1", method="get_output1"),
        Output(display_name="Output 2", name="output2", method="get_output2"),
        Output(display_name="Output 3", name="output3", method="get_output3"),
        Output(display_name="Output 4", name="output4", method="get_output4"),
    ]

    def parse_json(self):
        if not hasattr(self, 'json_input') or not self.json_input:
            self.status = "No JSON input provided"
            self.parsed_json = {}
            return
        try:
            self.parsed_json = json.loads(self.json_input)
            self.status = "JSON parsed successfully"
        except json.JSONDecodeError:
            self.status = "Invalid JSON input"
            self.parsed_json = {}
        except Exception as e:
            self.status = f"Error processing JSON: {str(e)}"
            self.parsed_json = {}

    def get_output(self, key_attr: str) -> Message:
        self.parse_json()
        
        key = getattr(self, key_attr, None)
        
        if key and key in self.parsed_json:
            value = self.parsed_json[key]
            if isinstance(value, list):
                # Convert list of lists to dictionary
                output_dict = {item[0]: item[1] for item in value}
            else:
                output_dict = value
            
            # Use ensure_ascii=False to preserve Unicode characters
            output_string = json.dumps(output_dict, ensure_ascii=False)
            self.status = f"{output_string}"
        else:
            output_string = "{}"
            self.status = f"Output for key '{key}': Key not found or not provided"
        
        return Message(text=output_string)

    def get_output1(self) -> Message:
        return self.get_output('key_1')

    def get_output2(self) -> Message:
        return self.get_output('key_2')

    def get_output3(self) -> Message:
        return self.get_output('key_3')
        
    def get_output4(self) -> Message:
        return self.get_output('key_4')
```

### Reproduction

using custom component, tested str, Text and Message Objects as outputs. Was trying to connect to Prompt or Pass .

### Expected behavior

it should work

### Operating System

Windows 11 pro

### Langflow Version

1.0.17

### Python Version

None

**Comment by nicoloboschi** [comment]
You're overriding `get_output`, please change the method name
