### ISSUE TITLE
CDK Deploy fails due to Cloud9 deprecation.

### ISSUE THREAD

**Issue by dfridkin** [langflow-ai/langflow#3894]
### Bug Description

Cloud9 is now deprecated, therefore anyone deploying on new aws accounts can not use the cdk stack provided.

### Reproduction

1. Create new AWS account.
2. Attempt to deploy the provided stack.

### Expected behavior

The cdk stack should deploy with no errors.

### Operating System

N/A

### Langflow Version

1.0.18

### Python Version

None

**Comment by dfridkin** [comment]
Trying to bypass cloud9 and deploying locally using aws cli and cdk cli I've run into the following issues:

Needed to move Dockerfiles, dockerignore, and .sh cdk helper script from docker to root directory due to inability to reference pyproject.toml in the parent directory during docker build.

Added cdk* to dockerignore to fix infinite recursion directory naming error (maximum length exceeded).

I then hit issues with alembic during cdk deploy once the tasks try to execute in the backend ecs cluster. Stuck trying to resolve this.

 2024-09-23 22:36:35 - ERROR    -     service.py:196
                             service - Error initializing                       
                             alembic:                                           
                             (pymysql.err.OperationalError)                     
                             (1072, "Key column                                 
                             'description' doesn't exist in                
                             table")                                            
                             [SQL: CREATE INDEX                                 
                             ix_flow_description ON flow                        
                             (`description`)]                              
                             (Background on this error at:                      
                             https://sqlalche.me/e/20/e3q8)

**Comment by Dmtmr** [comment]
Hi there, same issue here. Can someone get back back pls

**Comment by jolo-dev** [comment]
I ran into the same issue, but I believe this issue has nothing to do with Cloud9 @dfridkin

**Comment by dfridkin** [comment]
> I ran into the same issue, but I believe this issue has nothing to do with Cloud9 @dfridkin

That is true. There are multiple reasons cdk deploy is failing. Listed them above

**Comment by carlosrcoelho** [comment]
Do you need any assistance with this case? If not, please let us know if this issue can be closed.

**Comment by jolo-dev** [comment]
Hey @carlosrcoelho,

Let me push something until after Christmas.
Sorry, it took a while.

**Comment by jolo-dev** [comment]
Hi @carlosrcoelho,

I indeed need a bit of help.
You can find it in my [repo](https://github.com/jolo-dev/langflow/tree/cdk-deployment) on the branch `cdk-deployment`.
When creating the Dockerfile for CDK (`cdk.Dockerfile`), I get following error.

```sh
2025-01-06 22:46:27 Installing backend dependencies
2025-01-06 22:46:27 Audited 493 packages in 0.32ms
2025-01-06 22:46:27 /bin/sh: 1: lsof: not found
2025-01-06 22:46:27 /bin/sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
2025-01-06 22:46:27 kill -l [exitstatus]
2025-01-06 22:46:27 Running backend respecting the .env file
2025-01-06 22:46:27 uv run uvicorn \
2025-01-06 22:46:27 --factory langflow.main:create_app \
2025-01-06 22:46:27 --host 0.0.0.0 \
2025-01-06 22:46:27 --port 7860 \
2025-01-06 22:46:27  --reload \
2025-01-06 22:46:27 --env-file .env \
2025-01-06 22:46:27 --loop asyncio \
2025-01-06 22:46:27 --workers 1
2025-01-06 22:46:27 INFO:     Will watch for changes in these directories: ['/app']
2025-01-06 22:46:27 INFO:     Loading environment from '.env'
2025-01-06 22:46:27 INFO:     Uvicorn running on http://0.0.0.0:7860 (Press CTRL+C to quit)
2025-01-06 22:46:27 INFO:     Started reloader process [17] using WatchFiles
2025-01-06 22:46:32 2025-01-06 21:46:32.962 | DEBUG    | langflow.services.manager:_create_service:55 - Create service ServiceType.SETTINGS_SERVICE
2025-01-06 22:46:32 2025-01-06 21:46:32.993 | DEBUG    | langflow.services.settings.base:set_database_url:254 - No database_url provided, trying LANGFLOW_DATABASE_URL env variable
2025-01-06 22:46:32 2025-01-06 21:46:32.993 | DEBUG    | langflow.services.settings.base:set_database_url:257 - Using LANGFLOW_DATABASE_URL env variable.
2025-01-06 22:46:32 2025-01-06 21:46:32.993 | DEBUG    | langflow.services.settings.base:set_components_path:339 - Setting default components path to components_path
2025-01-06 22:46:32 2025-01-06 21:46:32.993 | DEBUG    | langflow.services.settings.base:set_components_path:344 - Components path: ['/app/src/backend/base/langflow/components']
2025-01-06 22:46:32 2025-01-06 21:46:32.993 | DEBUG    | langflow.services.settings.base:set_user_agent:206 - Setting user agent to langflow
2025-01-06 22:46:32 Process SpawnProcess-1:
2025-01-06 22:46:32 Traceback (most recent call last):
2025-01-06 22:46:32   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
2025-01-06 22:46:32     self.run()
2025-01-06 22:46:32   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
2025-01-06 22:46:32     self._target(*self._args, **self._kwargs)
2025-01-06 22:46:32   File "/app/.venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
2025-01-06 22:46:32     target(sockets=sockets)
2025-01-06 22:46:32   File "/app/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 66, in run
2025-01-06 22:46:32     return asyncio.run(self.serve(sockets=sockets))
2025-01-06 22:46:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
2025-01-06 22:46:32     return runner.run(main)
2025-01-06 22:46:32            ^^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
2025-01-06 22:46:32     return self._loop.run_until_complete(task)
2025-01-06 22:46:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
2025-01-06 22:46:32     return future.result()
2025-01-06 22:46:32            ^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "/app/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 70, in serve
2025-01-06 22:46:32     await self._serve(sockets)
2025-01-06 22:46:32   File "/app/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 77, in _serve
2025-01-06 22:46:32     config.load()
2025-01-06 22:46:32   File "/app/.venv/lib/python3.12/site-packages/uvicorn/config.py", line 435, in load
2025-01-06 22:46:32     self.loaded_app = import_from_string(self.app)
2025-01-06 22:46:32                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "/app/.venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
2025-01-06 22:46:32     module = importlib.import_module(module_str)
2025-01-06 22:46:32              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
2025-01-06 22:46:32     return _bootstrap._gcd_import(name[level:], package, level)
2025-01-06 22:46:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2025-01-06 22:46:32   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2025-01-06 22:46:32   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2025-01-06 22:46:32   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2025-01-06 22:46:32   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
2025-01-06 22:46:32   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-01-06 22:46:32   File "/app/src/backend/base/langflow/main.py", line 24, in <module>
2025-01-06 22:46:32     from langflow.api import health_check_router, log_router, router
2025-01-06 22:46:32   File "/app/src/backend/base/langflow/api/__init__.py", line 3, in <module>
2025-01-06 22:46:32     from langflow.api.router import router
2025-01-06 22:46:32   File "/app/src/backend/base/langflow/api/router.py", line 4, in <module>
2025-01-06 22:46:32     from langflow.api.v1 import (
2025-01-06 22:46:32   File "/app/src/backend/base/langflow/api/v1/__init__.py", line 8, in <module>
2025-01-06 22:46:32     from langflow.api.v1.mcp import router as mcp_router
2025-01-06 22:46:32   File "/app/src/backend/base/langflow/api/v1/mcp.py", line 48, in <module>
2025-01-06 22:46:32     enable_progress_notifications = get_settings_service().settings.mcp_server_enable_progress_notifications
2025-01-06 22:46:32                                     ^^^^^^^^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "/app/src/backend/base/langflow/services/deps.py", line 129, in get_settings_service
2025-01-06 22:46:32     return get_service(ServiceType.SETTINGS_SERVICE, SettingsServiceFactory())
2025-01-06 22:46:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "/app/src/backend/base/langflow/services/deps.py", line 48, in get_service
2025-01-06 22:46:32     return service_manager.get(service_type, default)
2025-01-06 22:46:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "/app/src/backend/base/langflow/services/manager.py", line 49, in get
2025-01-06 22:46:32     self._create_service(service_name, default)
2025-01-06 22:46:32   File "/app/src/backend/base/langflow/services/manager.py", line 74, in _create_service
2025-01-06 22:46:32     self.services[service_name] = self.factories[service_name].create(**dependent_services)
2025-01-06 22:46:32                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "/app/src/backend/base/langflow/services/settings/factory.py", line 22, in create
2025-01-06 22:46:32     return SettingsService.initialize()
2025-01-06 22:46:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-06 22:46:32   File "/app/src/backend/base/langflow/services/settings/service.py", line 20, in initialize
2025-01-06 22:46:32     settings = Settings()
2025-01-06 22:46:32                ^^^^^^^^^^
2025-01-06 22:46:32   File "/app/.venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 144, in __init__
2025-01-06 22:46:32     super().__init__(
2025-01-06 22:46:32   File "/app/.venv/lib/python3.12/site-packages/pydantic/main.py", line 214, in __init__
2025-01-06 22:46:32     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
2025-01-06 22:46:32                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-06 22:46:32 pydantic_core._pydantic_core.ValidationError: 7 validation errors for Settings
2025-01-06 22:46:32 save_db_in_config_dir
2025-01-06 22:46:32   Input should be a valid boolean, unable to interpret input [type=bool_parsing, input_value='', input_type=str]
2025-01-06 22:46:32     For further information visit https://errors.pydantic.dev/2.10/v/bool_parsing
2025-01-06 22:46:32 cache_type
2025-01-06 22:46:32   Input should be 'async', 'redis', 'memory' or 'disk' [type=literal_error, input_value='', input_type=str]
2025-01-06 22:46:32     For further information visit https://errors.pydantic.dev/2.10/v/literal_error
2025-01-06 22:46:32 remove_api_keys
2025-01-06 22:46:32   Input should be a valid boolean, unable to interpret input [type=bool_parsing, input_value='', input_type=str]
2025-01-06 22:46:32     For further information visit https://errors.pydantic.dev/2.10/v/bool_parsing
2025-01-06 22:46:32 store_environment_variables
2025-01-06 22:46:32   Input should be a valid boolean, unable to interpret input [type=bool_parsing, input_value='', input_type=str]
2025-01-06 22:46:32     For further information visit https://errors.pydantic.dev/2.10/v/bool_parsing
2025-01-06 22:46:32 port
2025-01-06 22:46:32   Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='', input_type=str]
2025-01-06 22:46:32     For further information visit https://errors.pydantic.dev/2.10/v/int_parsing
2025-01-06 22:46:32 workers
2025-01-06 22:46:32   Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='', input_type=str]
2025-01-06 22:46:32     For further information visit https://errors.pydantic.dev/2.10/v/int_parsing
2025-01-06 22:46:32 open_browser
2025-01-06 22:46:32   Input should be a valid boolean, unable to interpret input [type=bool_parsing, input_value='', input_type=str]
2025-01-06 22:46:32     For further information visit https://errors.pydantic.dev/2.10/v/bool_parsing
```
