### ISSUE TITLE
Cannot Start Langflow Using Pipenv Installation

### ISSUE THREAD

**Issue by karthicraghupathi** [langflow-ai/langflow#3996]
### Bug Description

Greetings!

I'm attempting to run Langflow in a virtual environment provided by `pipenv`. This should similar to the `pip` installation method. Here is my `Pipfile`:

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pip_conf_index_global"

[packages]
langflow = "*"

[dev-packages]

[requires]
python_version = "3.11"
python_full_version = "3.11.4"
```

When I proceed to install the dependencies and run Langflow, I get the following exception: `ModuleNotFoundError: No module named 'typing_extensions'`

When I check the dependency graph by running `pipenv graph`, I can see that `typing-extensions==4.12.2` is installed. I've attached the output of this command as a file as it is rather large.

[dependency_graph.txt](https://github.com/user-attachments/files/17236365/dependency_graph.txt)

Can you shed some light on what is going on?

### Reproduction

```
mkdir langflow && cd langflow
pipenv shell --python 3.11
pipenv install langflow
python -m langflow run
```

I end up with the following error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/karthicr/.local/share/virtualenvs/langflow-CJbw-fTq/lib/python3.11/site-packages/langflow/__main__.py", line 11, in <module>
    from langflow.utils.version import get_version_info, fetch_latest_version
  File "/Users/karthicr/.local/share/virtualenvs/langflow-CJbw-fTq/lib/python3.11/site-packages/langflow/utils/version.py", line 4, in <module>
    from langflow.logging.logger import logger
  File "/Users/karthicr/.local/share/virtualenvs/langflow-CJbw-fTq/lib/python3.11/site-packages/langflow/logging/__init__.py", line 1, in <module>
    from .logger import configure, logger
  File "/Users/karthicr/.local/share/virtualenvs/langflow-CJbw-fTq/lib/python3.11/site-packages/langflow/logging/logger.py", line 14, in <module>
    from typing_extensions import NotRequired
ModuleNotFoundError: No module named 'typing_extensions'
```

### Expected behavior

For Langflow to start up without any issues.

### Operating System

macOS Sonoma 14.16.1 on Apple M1 Max

### Langflow Version

1.0.18

### Python Version

3.11

**Comment by karthicraghupathi** [comment]
Thank you. The issue I reported seems to be from using an older version of `pipenv`. After updating `pipenv` and reinstalling `langflow`, I'm now able to successfully run it.
