### ISSUE TITLE
Error during make docker_build: Missing README.md causes OSError

### ISSUE THREAD

**Issue by roychen11232357** [langflow-ai/langflow#4075]
### Bug Description

I encountered an error while running the make docker_build command. The error occurred during the execution of uv sync --frozen --no-editable, with the following details:

```
 => CACHED [builder 13/15] ADD ./pyproject.toml /app/pyproject.toml                                                                                                                                         0.0s
 => CACHED [builder 14/15] ADD ./uv.lock /app/uv.lock                                                                                                                                                       0.0s
 => ERROR [builder 15/15] RUN --mount=type=cache,target=/root/.cache/uv     uv sync --frozen --no-editable                                                                                                  0.9s
------
 > [builder 15/15] RUN --mount=type=cache,target=/root/.cache/uv     uv sync --frozen --no-editable:
0.904 error: Failed to prepare distributions
0.904   Caused by: Failed to fetch wheel: langflow @ file:///app
0.904   Caused by: Build backend failed to build wheel through build_wheel (exit status: 1)
0.904
0.904 [stderr]
0.904 Traceback (most recent call last):
0.904   File "<string>", line 11, in <module>
0.904   File "/root/.cache/uv/builds-v0/.tmpuJtPpS/lib/python3.12/site-packages/hatchling/build.py", line 58, in build_wheel
0.904     return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
0.904                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.904   File "/root/.cache/uv/builds-v0/.tmpuJtPpS/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
0.904     self.metadata.validate_fields()
0.904   File "/root/.cache/uv/builds-v0/.tmpuJtPpS/lib/python3.12/site-packages/hatchling/metadata/core.py", line 266, in validate_fields
0.904     self.core.validate_fields()
0.904   File "/root/.cache/uv/builds-v0/.tmpuJtPpS/lib/python3.12/site-packages/hatchling/metadata/core.py", line 1376, in validate_fields
0.904     getattr(self, attribute)
0.904   File "/root/.cache/uv/builds-v0/.tmpuJtPpS/lib/python3.12/site-packages/hatchling/metadata/core.py", line 531, in readme
0.904     raise OSError(message)
0.904 OSError: Readme file does not exist: README.md
0.904
------
build_and_push.Dockerfile:63
--------------------
  62 |
  63 | >>> RUN --mount=type=cache,target=/root/.cache/uv \
  64 | >>>     uv sync --frozen --no-editable
  65 |
--------------------
ERROR: failed to solve: process "/bin/sh -c uv sync --frozen --no-editable" did not complete successfully: exit code: 2
make: *** [Makefile:352: dockerfile_build] Error 1
```

### Reproduction

Run  `make docker_build` from root path of langflow project

### Expected behavior

I expect the docker_build command to complete successfully and generate the corresponding Docker image.

### Operating System

Ubuntu 24.04

### Langflow Version

main branch (commit 04fa6351a25047bebeac8a492f06ca84070c2edc)

### Python Version

3.12

**Comment by carlosrcoelho** [comment]
The standard way to run Langflow via Docker can be done as follows:

```bash
docker run -p 7860:7860 langflowai/langflow:latest
```
(to run the latest version)

```bash
docker run --rm -p 7860:7860 langflowai/langflow:1.0.17
```
(to choose which version you want to install.)
