### ISSUE TITLE
"Hierarchical Crew" component issues (v1.0.19)

### ISSUE THREAD

**Issue by SavvySupport** [langflow-ai/langflow#4153]
### Bug Description

Can not run the "Hierarchical Crew" component after update. 

Error building Component Hierarchical Crew: 

[Errno 5] Input/output error

Traceback (most recent call last):
  File "/langflow/venv/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 726, in _build_results
    result = await initialize.loading.get_instance_results(
  File "/langflow/venv/lib/python3.10/site-packages/langflow/interface/initialize/loading.py", line 67, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
  File "/langflow/venv/lib/python3.10/site-packages/langflow/interface/initialize/loading.py", line 153, in build_component
    build_results, artifacts = await custom_component.build_results()
  File "/langflow/venv/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 707, in build_results
    return await self._build_with_tracing()
  File "/langflow/venv/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 695, in _build_with_tracing
    _results, _artifacts = await self._build_results()
  File "/langflow/venv/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 734, in _build_results
    result = await result
  File "/langflow/venv/lib/python3.10/site-packages/langflow/base/agents/crewai/crew.py", line 80, in build_output
    result = await crew.kickoff_async()
  File "/langflow/venv/lib/python3.10/site-packages/crewai/crew.py", line 394, in kickoff_async
    return await asyncio.to_thread(self.kickoff, inputs)
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/asyncio/futures.py", line 285, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/langflow/venv/lib/python3.10/site-packages/crewai/crew.py", line 348, in kickoff
    result, manager_metrics = self._run_hierarchical_process()  # type: ignore # Incompatible types in assignment (expression has type "str | dict[str, Any]", variable has type "str")
  File "/langflow/venv/lib/python3.10/site-packages/crewai/crew.py", line 501, in _run_hierarchical_process
    task_output = task.execute(
  File "/langflow/venv/lib/python3.10/site-packages/crewai/task.py", line 217, in execute
    result = self._execute(
  File "/langflow/venv/lib/python3.10/site-packages/crewai/task.py", line 226, in _execute
    result = agent.execute_task(
  File "/langflow/venv/lib/python3.10/site-packages/crewai/agent.py", line 185, in execute_task
    result = self.agent_executor.invoke(
  File "/langflow/venv/lib/python3.10/site-packages/langchain/chains/base.py", line 164, in invoke
    raise e
  File "/langflow/venv/lib/python3.10/site-packages/langchain/chains/base.py", line 154, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/langflow/venv/lib/python3.10/site-packages/crewai/agents/executor.py", line 80, in _call
    next_step_output = self._take_next_step(
  File "/langflow/venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 1314, in _take_next_step
    [
  File "/langflow/venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 1314, in <listcomp>
    [
  File "/langflow/venv/lib/python3.10/site-packages/crewai/agents/executor.py", line 256, in _iter_next_step
    observation = tool_usage.use(tool_calling, agent_action.log)
  File "/langflow/venv/lib/python3.10/site-packages/crewai/tools/tool_usage.py", line 101, in use
    return f"{self._use(tool_string=tool_string, tool=tool, calling=calling)}"  # type: ignore # BUG?: "_use" of "ToolUsage" does not return a value (it only ever returns None)
  File "/langflow/venv/lib/python3.10/site-packages/crewai/tools/tool_usage.py", line 195, in _use
    self._printer.print(content=f"\n\n{result}\n", color="purple")
  File "/langflow/venv/lib/python3.10/site-packages/crewai/utilities/printer.py", line 4, in print
    self._print_purple(content)
  File "/langflow/venv/lib/python3.10/site-packages/crewai/utilities/printer.py", line 21, in _print_purple
    print("\033[95m {}\033[00m".format(content))
OSError: [Errno 5] Input/output error

### Reproduction

1. Run the component 
2. Produces error message above 

### Expected behavior

Prior to update, the component ran as expected. 

### Operating System

macOS Ventura 13.5.1

### Langflow Version

1.0.19

### Python Version

3.10

### Screenshot

https://prnt.sc/eC5ShtUkC7vM

**Comment by phact** [comment]
Seems like a crew ai issue? 
https://github.com/crewAIInc/crewAI/blob/main/src/crewai/tools/tool_usage.py#L100-L102

**Comment by carlosrcoelho** [comment]
Despite the known error reported by Seb:  
https://github.com/crewAIInc/crewAI/blob/main/src/crewai/tools/tool_usage.py#L100-L102

A new version v1.0.19.post1 is out!
https://github.com/langflow-ai/langflow/releases/tag/v1.0.19.post1

Some issues related to CrewAI were fixed. Please try it out.

**Comment by carlosrcoelho** [comment]
![image](https://github.com/user-attachments/assets/2583bbfb-2fc3-4672-8cb2-06edc83c6527)


Working as expected in the new version.
