### ISSUE TITLE
v1.0.19, Simple Agent with Ollama: Error building component

### ISSUE THREAD

**Issue by PieBru** [langflow-ai/langflow#4178]
### Bug Description

![image](https://github.com/user-attachments/assets/cfd14608-96af-48cb-9503-6b5fd1b22dfa)

### Reproduction

I'm totally new in LangFlow, this is my first agent, I don't have an OpenAI API KEY so I use my local Ollama inference server.
I opened the Simple Agent and substituted the OpenAI LLM with the Ollama LLM, and used Ollama tool calling agent. Tryed also the generic Tools calling agent, same behaviour.
My Ollama inference server works.
The error displayed is not informative for me.

### Expected behavior

A working workflow.

### Operating System

Arch Linux, python3 venv

### Langflow Version

1.0.19

### Python Version

3.11

### Screenshot

![image](https://github.com/user-attachments/assets/273de04d-2f81-4ef2-95ab-3ae974f9d798)

### Flow File

[Simple Agent.json](https://github.com/user-attachments/files/17400212/Simple.Agent.json)

**Comment by PieBru** [comment]
@dosu, here is the console log:
```log
/usr/lib/python3.12/asyncio/base_events.py:726: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/pydantic/main.py:1086: PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
  warnings.warn(
/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py:293: PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
  warnings.warn(
[10/16/24 19:33:56] ERROR    2024-10-16 19:33:56 - ERROR    - base -                                                                                base.py:739
                             Traceback (most recent call last):                                                                                                
                                                                                                                                                               
                               File "/usr/lib/python3.12/threading.py", line 1032, in _bootstrap                                                               
                                 self._bootstrap_inner()                                                                                                       
                                 |    -> <function Thread._bootstrap_inner at 0x7010215f47c0>                                                                  
                                 -> <Thread(asyncio_0, started 123213854017216)>                                                                               
                               File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner                                                         
                                 self.run()                                                                                                                    
                                 |    -> <function Thread.run at 0x7010215f44a0>                                                                               
                                 -> <Thread(asyncio_0, started 123213854017216)>                                                                               
                               File "/usr/lib/python3.12/threading.py", line 1012, in run                                                                      
                                 self._target(*self._args, **self._kwargs)                                                                                     
                                 |    |        |    |        |    -> {}                                                                                        
                                 |    |        |    |        -> <Thread(asyncio_0, started 123213854017216)>                                                   
                                 |    |        |    -> (<weakref at 0x701017ab0130; to 'ThreadPoolExecutor' at 0x701017a555e0>, <_queue.SimpleQueue            
                             object at 0x701017968cc0>, None,...                                                                                               
                                 |    |        -> <Thread(asyncio_0, started 123213854017216)>                                                                 
                                 |    -> <function _worker at 0x70101e144f40>                                                                                  
                                 -> <Thread(asyncio_0, started 123213854017216)>                                                                               
                               File "/usr/lib/python3.12/concurrent/futures/thread.py", line 92, in _worker                                                    
                                 work_item.run()                                                                                                               
                                 |         -> <function _WorkItem.run at 0x70101e1465c0>                                                                       
                                 -> <concurrent.futures.thread._WorkItem object at 0x700fc0b32e40>                                                             
                               File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run                                                        
                                 result = self.fn(*self.args, **self.kwargs)                                                                                   
                                          |    |   |    |       |    -> {}                                                                                     
                                          |    |   |    |       -> <concurrent.futures.thread._WorkItem object at 0x700fc0b32e40>                              
                                          |    |   |    -> ()                                                                                                  
                                          |    |   -> <concurrent.futures.thread._WorkItem object at 0x700fc0b32e40>                                           
                                          |    -> functools.partial(<built-in method run of _contextvars.Context object at 0x700fc0c68740>,                    
                             <function _patch_asyncio.<locals>.r...                                                                                            
                                          -> <concurrent.futures.thread._WorkItem object at 0x700fc0b32e40>                                                    
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/nest_asyncio            
                             .py", line 30, in run                                                                                                             
                                 return loop.run_until_complete(task)                                                                                          
                                        |    |                  -> <Task pending name='Task-485' coro=<build_flow.<locals>._build_vertex() running             
                             at /mnt/00aadc36-3e91-4512-b272-3e84356ac527/...                                                                                  
                                        |    -> <function _patch_loop.<locals>.run_until_complete at 0x701017b4a480>                                           
                                        -> <_UnixSelectorEventLoop running=True closed=False debug=False>                                                      
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/nest_asyncio            
                             .py", line 92, in run_until_complete                                                                                              
                                 self._run_once()                                                                                                              
                                 |    -> <function _patch_loop.<locals>._run_once at 0x701017b4a520>                                                           
                                 -> <_UnixSelectorEventLoop running=True closed=False debug=False>                                                             
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/nest_asyncio            
                             .py", line 133, in _run_once                                                                                                      
                                 handle._run()                                                                                                                 
                                 |      -> <function Handle._run at 0x70101ff7b1a0>                                                                            
                                 -> <Handle Task.__step()>                                                                                                     
                               File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run                                                                  
                                 self._context.run(self._callback, *self._args)                                                                                
                                 |    |            |    |           |    -> <member '_args' of 'Handle' objects>                                               
                                 |    |            |    |           -> <Handle Task.__step()>                                                                  
                                 |    |            |    -> <member '_callback' of 'Handle' objects>                                                            
                                 |    |            -> <Handle Task.__step()>                                                                                   
                                 |    -> <member '_context' of 'Handle' objects>                                                                               
                                 -> <Handle Task.__step()>                                                                                                     
                               File "/usr/lib/python3.12/asyncio/tasks.py", line 303, in __step                                                                
                                 self.__step_run_and_handle_result(exc)                                                                                        
                                 |                                 -> None                                                                                     
                                 -> <Task pending name='Task-485' coro=<build_flow.<locals>._build_vertex() running at                                         
                             /mnt/00aadc36-3e91-4512-b272-3e84356ac527/...                                                                                     
                               File "/usr/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result                                          
                                 result = coro.send(None)                                                                                                      
                                          |    -> <method 'send' of 'coroutine' objects>                                                                       
                                          -> <coroutine object build_flow.<locals>._build_vertex at 0x5c9629f12c70>                                            
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/api            
                             /v1/chat.py", line 219, in _build_vertex                                                                                          
                                 vertex_build_result = await graph.build_vertex(                                                                               
                                                             |     -> <function Graph.build_vertex at 0x700ff4c9e980>                                          
                                                             -> Graph Representation:                                                                          
                                                                ----------------------                                                                         
                                                                Vertices (6):                                                                                  
                                                                  ChatInput-IpoUd, ChatOutput-jsL2n, CalculatorTool-5pzp2, PythonR...                          
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/gra            
                             ph/graph/base.py", line 1384, in build_vertex                                                                                     
                                 await vertex.build(                                                                                                           
                                       |      -> <function Vertex.build at 0x700ff4c960c0>                                                                     
                                       -> Vertex(display_name=Tool Calling Agent, id=ToolCallingAgent-w3GPA, data={'type': 'ToolCallingAgent',                 
                             'node': {'template': {'_...                                                                                                       
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/gra            
                             ph/vertex/base.py", line 832, in build                                                                                            
                                 await step(user_id=user_id, event_manager=event_manager, **kwargs)                                                            
                                       |            |                      |                -> {'fallback_to_env_vars': False}                                 
                                       |            |                      -> <langflow.events.event_manager.EventManager object at 0x700fcce999a0>            
                                       |            -> UUID('4b2c08c9-7d77-4805-b505-946c5999c785')                                                            
                                       -> <bound method Vertex._build of Vertex(display_name=Tool Calling Agent, id=ToolCallingAgent-w3GPA,                    
                             data={'type': 'ToolCallingA...                                                                                                    
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/gra            
                             ph/vertex/base.py", line 501, in _build                                                                                           
                                 await self._build_results(                                                                                                    
                                       |    -> <function Vertex._build_results at 0x700ff4c95d00>                                                              
                                       -> Vertex(display_name=Tool Calling Agent, id=ToolCallingAgent-w3GPA, data={'type': 'ToolCallingAgent',                 
                             'node': {'template': {'_...                                                                                                       
                             > File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/gra            
                             ph/vertex/base.py", line 726, in _build_results                                                                                   
                                 result = await initialize.loading.get_instance_results(                                                                       
                                                |          |       -> <function get_instance_results at 0x70101e005bc0>                                        
                                                |          -> <module 'langflow.interface.initialize.loading' from                                             
                             '/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/...                                                       
                                                -> <module 'langflow.interface.initialize' from                                                                
                             '/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib...                                               
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/int            
                             erface/initialize/loading.py", line 67, in get_instance_results                                                                   
                                 return await build_component(params=custom_params, custom_component=custom_component)                                         
                                              |                      |                               ->                                                        
                             <langflow.utils.validate.ToolCallingAgentComponent object at 0x700fcd584d70>                                                      
                                              |                      -> {'tools': [StructuredTool(name='PythonREPLTool', description='A tool for               
                             running Python code in a REPL environment.', args_sc...                                                                           
                                              -> <function build_component at 0x700ff4c93ec0>                                                                  
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/int            
                             erface/initialize/loading.py", line 153, in build_component                                                                       
                                 build_results, artifacts = await custom_component.build_results()                                                             
                                                                  |                -> <function Component.build_results at 0x700ff4c93740>                     
                                                                  -> <langflow.utils.validate.ToolCallingAgentComponent object at 0x700fcd584d70>              
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/cus            
                             tom/custom_component/component.py", line 707, in build_results                                                                    
                                 return await self._build_with_tracing()                                                                                       
                                              |    -> <function Component._build_with_tracing at 0x700ff4c93600>                                               
                                              -> <langflow.utils.validate.ToolCallingAgentComponent object at 0x700fcd584d70>                                  
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/cus            
                             tom/custom_component/component.py", line 695, in _build_with_tracing                                                              
                                 _results, _artifacts = await self._build_results()                                                                            
                                                              |    -> <function Component._build_results at 0x700ff4c937e0>                                    
                                                              -> <langflow.utils.validate.ToolCallingAgentComponent object at 0x700fcd584d70>                  
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/cus            
                             tom/custom_component/component.py", line 734, in _build_results                                                                   
                                 result = await result                                                                                                         
                                                -> <coroutine object LCAgentComponent.message_response at 0x700fc0caaa40>                                      
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/bas            
                             e/agents/agent.py", line 58, in message_response                                                                                  
                                 agent = self.build_agent()                                                                                                    
                                         |    -> <function LCToolsAgentComponent.build_agent at 0x700fd7db8860>                                                
                                         -> <langflow.utils.validate.ToolCallingAgentComponent object at 0x700fcd584d70>                                       
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/bas            
                             e/agents/agent.py", line 122, in build_agent                                                                                      
                                 agent = self.create_agent_runnable()                                                                                          
                                         |    -> <function ToolCallingAgentComponent.create_agent_runnable at 0x700fccea0fe0>                                  
                                         -> <langflow.utils.validate.ToolCallingAgentComponent object at 0x700fcd584d70>                                       
                               File "<string>", line 46, in create_agent_runnable                                                                              
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langchain/ag            
                             ents/tool_calling_agent/base.py", line 98, in create_tool_calling_agent                                                           
                                 llm_with_tools = llm.bind_tools(tools)                                                                                        
                                                  |   |          -> [StructuredTool(name='PythonREPLTool', description='A tool for running Python              
                             code in a REPL environment.', args_schema=<clas...                                                                                
                                                  |   -> <function BaseChatModel.bind_tools at 0x70101c845800>                                                 
                                                  -> ChatOllama(metadata={}, model='phi3.5:latest', mirostat=0, temperature=0.2, system='',                    
                             template='', format='')                                                                                                           
                               File                                                                                                                            
                             "/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langchain_co            
                             re/language_models/chat_models.py", line 1120, in bind_tools                                                                      
                                 raise NotImplementedError()                                                                                                   
                                                                                                                                                               
                             NotImplementedError                                                                                                               
                                                                                                                                                               
                             ╭──────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────╮            
                             │ /mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/ │            
                             │ graph/vertex/base.py:726 in _build_results                                                                         │            
                             │                                                                                                                    │            
                             │   723 │                                                                                                            │            
                             │   724 │   async def _build_results(self, custom_component, custom_params,                                          │            
                             │       fallback_to_env_vars=False):                                                                                 │            
                             │   725 │   │   try:                                                                                                 │            
                             │ ❱ 726 │   │   │   result = await initialize.loading.get_instance_results(                                          │            
                             │   727 │   │   │   │   custom_component=custom_component,                                                           │            
                             │   728 │   │   │   │   custom_params=custom_params,                                                                 │            
                             │   729 │   │   │   │   vertex=self,                                                                                 │            
                             │                                                                                                                    │            
                             │ /mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/ │            
                             │ interface/initialize/loading.py:67 in get_instance_results                                                         │            
                             │                                                                                                                    │            
                             │    64 │   │   if base_type == "custom_components":                                                                 │            
                             │    65 │   │   │   return await build_custom_component(params=custom_params,                                        │            
                             │       custom_component=custom_component)                                                                           │            
                             │    66 │   │   if base_type == "component":                                                                         │            
                             │ ❱  67 │   │   │   return await build_component(params=custom_params,                                               │            
                             │       custom_component=custom_component)                                                                           │            
                             │    68 │   │   msg = f"Base type {base_type} not found."                                                            │            
                             │    69 │   │   raise ValueError(msg)                                                                                │            
                             │    70                                                                                                              │            
                             │                                                                                                                    │            
                             │ /mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/ │            
                             │ interface/initialize/loading.py:153 in build_component                                                             │            
                             │                                                                                                                    │            
                             │   150 ):                                                                                                           │            
                             │   151 │   # Now set the params as attributes of the custom_component                                               │            
                             │   152 │   custom_component.set_attributes(params)                                                                  │            
                             │ ❱ 153 │   build_results, artifacts = await custom_component.build_results()                                        │            
                             │   154 │                                                                                                            │            
                             │   155 │   return custom_component, build_results, artifacts                                                        │            
                             │   156                                                                                                              │            
                             │                                                                                                                    │            
                             │ /mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/ │            
                             │ custom/custom_component/component.py:707 in build_results                                                          │            
                             │                                                                                                                    │            
                             │   704 │   │   self,                                                                                                │            
                             │   705 │   ):                                                                                                       │            
                             │   706 │   │   if self._tracing_service:                                                                            │            
                             │ ❱ 707 │   │   │   return await self._build_with_tracing()                                                          │            
                             │   708 │   │   return await self._build_without_tracing()                                                           │            
                             │   709 │                                                                                                            │            
                             │   710 │   async def _build_results(self):                                                                          │            
                             │                                                                                                                    │            
                             │ /mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/ │            
                             │ custom/custom_component/component.py:695 in _build_with_tracing                                                    │            
                             │                                                                                                                    │            
                             │   692 │   │   inputs = self.get_trace_as_inputs()                                                                  │            
                             │   693 │   │   metadata = self.get_trace_as_metadata()                                                              │            
                             │   694 │   │   async with self._tracing_service.trace_context(self, self.trace_name, inputs,                        │            
                             │       metadata):                                                                                                   │            
                             │ ❱ 695 │   │   │   _results, _artifacts = await self._build_results()                                               │            
                             │   696 │   │   │   self._tracing_service.set_outputs(self.trace_name, _results)                                     │            
                             │   697 │   │                                                                                                        │            
                             │   698 │   │   return _results, _artifacts                                                                          │            
                             │                                                                                                                    │            
                             │ /mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/ │            
                             │ custom/custom_component/component.py:734 in _build_results                                                         │            
                             │                                                                                                                    │            
                             │   731 │   │   │   │   │   │   result = method()                                                                    │            
                             │   732 │   │   │   │   │   │   # If the method is asynchronous, we need to await it                                 │            
                             │   733 │   │   │   │   │   │   if inspect.iscoroutinefunction(method):                                              │            
                             │ ❱ 734 │   │   │   │   │   │   │   result = await result                                                            │            
                             │   735 │   │   │   │   │   │   if (                                                                                 │            
                             │   736 │   │   │   │   │   │   │   self._vertex is not None                                                         │            
                             │   737 │   │   │   │   │   │   │   and isinstance(result, Message)                                                  │            
                             │                                                                                                                    │            
                             │ /mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/ │            
                             │ base/agents/agent.py:58 in message_response                                                                        │            
                             │                                                                                                                    │            
                             │    55 │                                                                                                            │            
                             │    56 │   async def message_response(self) -> Message:                                                             │            
                             │    57 │   │   """Run the agent and return the response."""                                                         │            
                             │ ❱  58 │   │   agent = self.build_agent()                                                                           │            
                             │    59 │   │   result = await self.run_agent(agent=agent)                                                           │            
                             │    60 │   │                                                                                                        │            
                             │    61 │   │   if isinstance(result, list):                                                                         │            
                             │                                                                                                                    │            
                             │ /mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langflow/ │            
                             │ base/agents/agent.py:122 in build_agent                                                                            │            
                             │                                                                                                                    │            
                             │   119 │   ]                                                                                                        │            
                             │   120 │                                                                                                            │            
                             │   121 │   def build_agent(self) -> AgentExecutor:                                                                  │            
                             │ ❱ 122 │   │   agent = self.create_agent_runnable()                                                                 │            
                             │   123 │   │   return AgentExecutor.from_agent_and_tools(                                                           │            
                             │   124 │   │   │   agent=RunnableAgent(runnable=agent, input_keys_arg=["input"],                                    │            
                             │       return_keys_arg=["output"]),                                                                                 │            
                             │   125 │   │   │   tools=self.tools,                                                                                │            
                             │ in create_agent_runnable:46                                                                                        │            
                             │                                                                                                                    │            
                             │ /mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langchain │            
                             │ /agents/tool_calling_agent/base.py:98 in create_tool_calling_agent                                                 │            
                             │                                                                                                                    │            
                             │    95 │   │   raise ValueError(                                                                                    │            
                             │    96 │   │   │   "This function requires a .bind_tools method be implemented on the LLM.",                        │            
                             │    97 │   │   )                                                                                                    │            
                             │ ❱  98 │   llm_with_tools = llm.bind_tools(tools)                                                                   │            
                             │    99 │                                                                                                            │            
                             │   100 │   agent = (                                                                                                │            
                             │   101 │   │   RunnablePassthrough.assign(                                                                          │            
                             │                                                                                                                    │            
                             │ /mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/langchain │            
                             │ _core/language_models/chat_models.py:1120 in bind_tools                                                            │            
                             │                                                                                                                    │            
                             │   1117 │   │   tools: Sequence[Union[Dict[str, Any], Type, Callable, BaseTool]],                                   │            
                             │   1118 │   │   **kwargs: Any,                                                                                      │            
                             │   1119 │   ) -> Runnable[LanguageModelInput, BaseMessage]:                                                         │            
                             │ ❱ 1120 │   │   raise NotImplementedError()                                                                         │            
                             │   1121 │                                                                                                           │            
                             │   1122 │   def with_structured_output(                                                                             │            
                             │   1123 │   │   self,                                                                                               │            
                             ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯            
                             NotImplementedError                                                                                                               
/mnt/00aadc36-3e91-4512-b272-3e84356ac527/Piero/AI_Lab/Github/langflow/venv/lib/python3.12/site-packages/pydantic/main.py:1086: PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
  warnings.warn(
```

**Comment by PieBru** [comment]
I'm not a python coder, so if you give me a patch to address these issues I will be more than happy to try it locally.
Thank you,
Piero

**Comment by joaoguilhermeS** [comment]
Hi @PieBru, 

Currently, using Ollama with the Agents components directly isn't possible due to compatibility issues. However, the team is actively working on a fix for this.

In the meantime, it's possible to use tools with Ollama through a custom component that implements a different approach to agents. I've modified the Tool Calling Agent using this tutorial: [Basic Llama 3.2 3B Tool Calling with LangChain and Ollama](https://medium.com/@Netanel-m/basic-llama-3-2-3b-tool-calling-with-langchain-and-ollama-47ad29b11f34).

Here’s a basic implementation that you can try adding on your component:

```
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
from langchain_core.messages.system import SystemMessage
from langchain import hub
from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain_ollama import ChatOllama

# modifying tool
@tool
def pig_latin(phrase) -> str:
    """Returns the pig latin pronounciation of a phrase"""
    def convert_word(word) -> str:
        if word[0] in "aeiouAEIOU":
            return word + "way"
        else:
            for index, letter in enumerate(word):
                if letter in "aeiouAEIOU":
                    return word[index:] + word[:index] + "ay"
            return word + "ay"

    words = phrase.split()
    pig_latin_words = [convert_word(word) for word in words]
    return " ".join(pig_latin_words)   

tools = [pig_latin]
model = ChatOllama(model="llama3.2:3b").bind_tools(tools)
prompt = hub.pull("hwchase17/openai-tools-agent")
prompt.pretty_print()

agent = create_tool_calling_agent(model, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

return agent_executor
```

However, this approach requires explicitly using tools through custom code, which might not suit your needs.

I’ve also spoken with the LF Team, and support for Agents in Ollama is expected soon.

**Comment by joaoguilhermeS** [comment]
@PieBru Just to mention here, I tested it again with the preview version, and this issue is fixed, in the **1.1 Release** you can use Ollama with tool calling agent.

**Comment by rpcoelho23** [comment]
Hi All,
I am working with version 1.1.1 and I am having the same issue.  I am trying to use Ollama with the Python REPL and I get the same error with LangFlow 1.1.1.  I work for Encora U.S.A and would appreciate if someone could point me to the code of the new agent so that I can just paste it over the agent of the ginormous flow that I built expecting that in the end an agent could summarize some information for me.

**Comment by avsilva** [comment]
@joaoguilhermeS could you please show us the flow that you are using (maybe a print screen should suffice). I'm getting "Result not found for component_as_tool. Results: {}. I think I'm not connecting the components the right way

**Comment by icemagno** [comment]
Why can't we just use local ollama server as one of that providers? This simply makes me to not use LangFlow at all. I can't use online servers.
