### ISSUE TITLE
How am I supposed to install new pip packages?

### ISSUE THREAD

**Issue by espogian** [langflow-ai/langflow#4594]
### Bug Description

I'm using langflow with Docker Compose. I have tried to create a custom model which leverages the Python module `transformers`, but the front-end is always throwing back an error of `module not found`, even after installation through `pip install transformers`.

### Reproduction

1. Create the following Dockerfile:

```
FROM langflowai/langflow:latest

RUN pip install transformers

CMD ["python", "-m", "langflow", "run", "--host", "0.0.0.0", "--port", "7860"]
```

2. Create the following docker-compose.yml file:

```
services:
  langflow:
    build: .
    container_name: langflow
    ports:
      - 7860:7860
```

3. Run `docker compose up -d --build`
4. Open http://localhost:7860
5. Try to create a new Custom Component with the following code (it is sufficient that the module imports `tranformers`):

```
# Import necessary modules
from langflow.custom import Component
from langflow.io import MessageTextInput, Output
from langflow.schema import Data

# Import transformers and LlamaTokenizer
from transformers import LlamaTokenizer

class CustomComponent(Component):
    display_name = "LLaMA Token Counter Component"
    description = "Counts the total tokens in the input text using LLaMA tokenization."
    documentation: str = "http://docs.langflow.org/components/custom"
    icon = "code"
    name = "LlamaTokenCounterComponent"

    # Define the input and output fields
    inputs = [
        MessageTextInput(
            name="input_text",
            display_name="Input Text",
            info="Enter the text for which you want to count tokens",
            value="",
            tool_mode=True,
        ),
    ]

    outputs = [
        Output(display_name="Token Count", name="token_count", method="count_tokens"),
    ]

    # Initialize the tokenizer for the LLaMA model
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Replace the model path below with the specific LLaMA model path you are using
        self.tokenizer = LlamaTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf")

    # Method to count tokens in the input text
    def count_tokens(self) -> Data:
        # Get the input text from the component
        input_text = self.input_text

        # Tokenize the input text
        tokens = self.tokenizer.encode(input_text)

        # Calculate the token count
        token_count = len(tokens)

        # Prepare and return the output data
        data = Data(value=token_count)
        self.status = data
        return data
```

### Expected behavior

Langflow web interface throws back the following error:

```
Error building Component: Module transformers not found. Please install it and try again
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/langflow/utils/validate.py", line 231, in prepare_global_scope
    imported_module = importlib.import_module(node.module)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
```

### Operating System

macOS Sequoia 15.1

### Langflow Version

1.1.0

### Python Version

3.12

**Comment by mataide** [comment]
There is a simple way:

```
FROM langflowai/langflow:v1.0.19.post2

# Install pip in the virtual environment
RUN /app/.venv/bin/python -m ensurepip --upgrade

# Install the unstructured-ingest module using the pip from the virtual environment
RUN /app/.venv/bin/python -m pip install unstructured-ingest

# Set the environment variable to use the virtual environment’s Python by default
ENV PATH="/app/.venv/bin:$PATH"

CMD ["python", "-m", "langflow", "run", "--host", "0.0.0.0", "--port", "7860"]
```
