### ISSUE TITLE
issue with langflow + crewai

### ISSUE THREAD

**Issue by fsilveira060** [langflow-ai/langflow#4645]
### Bug Description

the node agent: Sequential Crew does not run.
![image](https://github.com/user-attachments/assets/18a6093f-544b-4102-8edf-a698ef77ab6a)

Error Building Component
Error building Component Sequential Crew: argument of type 'NoneType' is not iterable

Input Receive:
Agent: Agent(role=Escritor, goal=Escrever um roteiro de vídeo do Youtube, backstory=Roteirista de Youtube Sensacionalista. Precisa escrever um roteiro de vídeo para um público alvo de 20 a 40 anos)
Task: Task(description=Escrever um roteiro sobre os temas listados na tarefa anterior, expected_output=Roteiro com o melhor formato para ser gerado um vídeo utilizando inteligência artificial)

### Reproduction

1- Create an empty flow
2- create an sequential crew

### Expected behavior

error message as provided with an issue about the input of node

### Operating System

Windows 11

### Langflow Version

1.1.0

### Python Version

3.11

### Screenshot

![image](https://github.com/user-attachments/assets/be9cd358-240b-4771-ac4a-d028fb6b8ac5)

**Comment by sharvareemane** [comment]
Same issue with with me as well.

**Comment by sharvareemane** [comment]
Error building Component Sequential Crew: 

argument of type 'NoneType' is not iterable

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 810, in completion
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 746, in completion
    self.make_sync_openai_chat_completion_request(
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 605, in make_sync_openai_chat_completion_request
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 594, in make_sync_openai_chat_completion_request
    raw_response = openai_client.chat.completions.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_legacy_response.py", line 356, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langfuse/openai.py", line 179, in wrapper
    return func(open_ai_definitions, initialize, wrapped, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langfuse/openai.py", line 587, in _wrap
    raise ex
  File "/app/.venv/lib/python3.12/site-packages/langfuse/openai.py", line 550, in _wrap
    openai_response = wrapped(**arg_extractor.get_openai_args())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 815, in create
    return self._post(
           ^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1058, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: dummy. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1527, in completion
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1500, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 820, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: dummy. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 837, in build_results
    return await self._build_with_tracing()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 819, in _build_with_tracing
    _results, _artifacts = await self._build_results()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 883, in _build_results
    result = await method()
             ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/base/agents/crewai/crew.py", line 80, in build_output
    result = await crew.kickoff_async()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/crew.py", line 532, in kickoff_async
    return await asyncio.to_thread(self.kickoff, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/crew.py", line 493, in kickoff
    result = self._run_sequential_process()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/crew.py", line 597, in _run_sequential_process
    return self._execute_tasks(self.tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/crew.py", line 695, in _execute_tasks
    task_output = task.execute_sync(
                  ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/task.py", line 191, in execute_sync
    return self._execute_core(agent, context, tools)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/task.py", line 247, in _execute_core
    result = agent.execute_task(
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/agent.py", line 240, in execute_task
    result = self.execute_task(task, context, tools)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/agent.py", line 240, in execute_task
    result = self.execute_task(task, context, tools)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/agent.py", line 239, in execute_task
    raise e
  File "/app/.venv/lib/python3.12/site-packages/crewai/agent.py", line 228, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 93, in invoke
    formatted_answer = self._invoke_loop()
                       ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 175, in _invoke_loop
    raise e
  File "/app/.venv/lib/python3.12/site-packages/crewai/agents/crew_agent_executor.py", line 115, in _invoke_loop
    answer = self.llm.call(
             ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/crewai/llm.py", line 155, in call
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1071, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 959, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2957, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2131, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 358, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: litellm.AuthenticationError: AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: dummy. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 708, in _build_results
    result = await initialize.loading.get_instance_results(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 68, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 145, in build_component
    build_results, artifacts = await custom_component.build_results()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 848, in build_results
    self.send_error(
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 1128, in send_error
    error_message = ErrorMessage(
                    ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/schema/message.py", line 359, in __init__
    if hasattr(exception, "body") and "message" in exception.body:
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by osoluche** [comment]
![image](https://github.com/user-attachments/assets/c392569f-d993-4e6e-82b0-665fa519fbc1)

Same problem here,  osx, langflow==1.1.0

**Comment by chyna-gvng** [comment]
![langflow-crewai](https://github.com/user-attachments/assets/6d19d3d2-cae9-4028-a21a-d4ead46bf92c)

Same issue on Hierachical Crew.
Langflow: 1.1.0

**Comment by ogabrielluiz** [comment]
Hey @osoluche and others.
How are you all? 


This could be related to #4638 . We will have a fix for this in our next release soon.

**Comment by ChunJen** [comment]
> Hey @osoluche and others. How are you all?
> 
> This could be related to #4638 . We will have a fix for this in our next release soon.

Hi @osoluche. It still happens in langflow version 1.1.1
![image](https://github.com/user-attachments/assets/a4dc04d6-29ca-457f-ac2a-9f01d48b9101)

Is there any solution for this bug?

**Comment by erichare** [comment]
@ChunJen this is fixed in the latest main branch. Please confirm.

**Comment by imrohankataria** [comment]
> @ChunJen this is fixed in the latest main branch. Please confirm.

Not yet fixed

**Comment by DCJsenior** [comment]
This issue still exists in the 1.1.1 version of the hierarchical crewai, can we release a new version as soon as possible to solve this problem?

**Comment by vbg1219** [comment]
I am still facing this issue.

**Comment by Nuneshere** [comment]
still facing the issue too.

**Comment by rafaelferreirapt** [comment]
I am facing this issue.

**Comment by eganjonez** [comment]
Still an Issue in 1.3.4, desktop and 1.3.3 uv install

**Comment by nichmorgan** [comment]
Same issue here!

**Comment by Victor-w-Madeira** [comment]
The CrewAI components are now considered legacy and are no longer maintained in the latest versions of Langflow.
