### ISSUE TITLE
SQL Query component doesn't work 

### ISSUE THREAD

**Issue by SavvySupport** [langflow-ai/langflow#4662]
### Bug Description

When I try to run a query, it gives me an error:
'SQLExecutorComponent' object has no attribute 'set_event_manager'

### Reproduction

1. Using the "SQL Query" component, enter in DB URL, and query. 
2. Run the component
3. It provides the following error message:

'SQLExecutorComponent' object has no attribute 'set_event_manager'

Traceback (most recent call last):
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/api/v1/chat.py", line 227, in _build_vertex
    vertex_build_result = await graph.build_vertex(
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/graph/graph/base.py", line 1419, in build_vertex
    await vertex.build(
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 818, in build
    await step(user_id=user_id, event_manager=event_manager, **kwargs)
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 493, in _build
    self.custom_component.set_event_manager(event_manager)
AttributeError: 'SQLExecutorComponent' object has no attribute 'set_event_manager'

### Expected behavior

Expected to return the queried results. 

### Operating System

MacOS

### Langflow Version

1.1

### Python Version

3.10

**Comment by SavvySupport** [comment]
Thanks @ogabrielluiz ! When will these fixes be pushed?
