### ISSUE TITLE
SQLAgent requiring "chat_history"? 

### ISSUE THREAD

**Issue by SavvySupport** [langflow-ai/langflow#4663]
### Bug Description

The SQLAgent shows error "chat_history not found in SQLAgentComponent". 

### Reproduction

1. Build a flow with "OpenAI" (or equivalent LLM) and "SQLAgent" component
2. Enter in API key for OpenAI, input and database URI for SQLAgent
3. Run the SQLAgent
4. Returns error below

Error building Component SQLAgent: 

chat_history not found in SQLAgentComponent

Traceback (most recent call last):
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 708, in _build_results
    result = await initialize.loading.get_instance_results(
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/interface/initialize/loading.py", line 68, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/interface/initialize/loading.py", line 145, in build_component
    build_results, artifacts = await custom_component.build_results()
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 837, in build_results
    return await self._build_with_tracing()
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 819, in _build_with_tracing
    _results, _artifacts = await self._build_results()
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 883, in _build_results
    result = await method()
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/base/agents/agent.py", line 81, in message_response
    message = await self.run_agent(agent=agent)
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/base/agents/agent.py", line 136, in run_agent
    if self.chat_history:
  File "/langflow1.1.0/venv1.1.0/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 665, in __getattr__
    raise AttributeError(msg)
AttributeError: chat_history not found in SQLAgentComponent

### Expected behavior

Expecting a response from the SQLAgent, instead of an error message for "chat_history"

### Operating System

MacOS

### Langflow Version

1.1

### Python Version

3.10

### Screenshot

<img width="496" alt="Screenshot 2024-11-18 at 5 03 33 pm" src="https://github.com/user-attachments/assets/02d15b4f-33c9-4b0a-8f9d-2c989deda86d">
<img width="505" alt="Screenshot 2024-11-18 at 5 03 56 pm" src="https://github.com/user-attachments/assets/3c26c21b-a080-45b4-83c2-18d2680ab0c2">

**Comment by ogabrielluiz** [comment]
Thanks for the report, @SavvySupport ! 

They were very helpful in pinpointing the bug.

**Comment by SavvySupport** [comment]
> Thanks for the report, @SavvySupport !
> 
> They were very helpful in pinpointing the bug.

No worries @ogabrielluiz ! Do you know when the fixes will be released?

**Comment by nec330** [comment]
this issue already had fixed ?
