### ISSUE TITLE
'folder_id - UUID input should be a string, bytes or UUID object' when starting in backend mode with LANGFLOW_LOAD_FLOWS_PATH

### ISSUE THREAD

**Issue by amomra** [langflow-ai/langflow#4889]
### Bug Description

I'm trying to start a pod in Kubernetes running the ``langflowai/langflow-backend:v1.1.1`` image (also tested with ``langflowai/langflow:v1.1.1`` image) with a flow that was exported from another langflow instance. I adjusted the ``LANGFLOW_LOAD_FLOWS_PATH`` to a path where I mounted a config map with the flow file. The pod starts but it keeps restarting because of the following error:

```
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/main.py", line 108, in lifespan
    await load_flows_from_directory()
  File "/app/.venv/lib/python3.12/site-packages/langflow/initial_setup/setup.py", line 587, in load_flows_from_directory
    flow = Flow.model_validate(flow, from_attributes=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/sqlmodel/main.py", line 760, in model_validate
    return sqlmodel_validate(
           ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/sqlmodel/_compat.py", line 313, in sqlmodel_validate
    cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for Flow
folder_id
  UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=<coroutine object get_def...er_id at 0x7f02e0d0e4d0>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.7/v/uuid_type
```

The flow file was attached in this issue. This is the Kubernetes deployment file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langflow-teste-backend
  namespace: langflow
spec:
  selector:
    matchLabels:
      app: langflow-teste-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: langflow-teste-backend
    spec:
      containers:
      - name: langflow-teste-backend
        image: langflowai/langflow-backend:v1.1.1
        command:
        - /bin/bash
        args:
        - -c
        - langflow run --backend-only --host 0.0.0.0 --port 7860
        ports:
        - containerPort: 7860
          name: web
        resources: {}
        env:
        - name: COLUMNS
          value: "200"
        - name: LANGFLOW_VARIABLES_TO_GET_FROM_ENVIRONMENT
          value: AZURE_OPENAI_API_DEPLOYMENT_NAME,AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME,AZURE_OPENAI_API_KEY,AZURE_OPENAI_API_VERSION,AZURE_OPENAI_API_ENDPOINT
        - name: LANGFLOW_LOAD_FLOWS_PATH
          value: /app/flows
        envFrom:
        - secretRef:
            name: openai-config
        volumeMounts:
        - name: teste-flows
          mountPath: /app/flows
        - name: data-volume
          mountPath: /app/data/
      volumes:
      - name: teste-flows
        configMap:
          name: teste-flows
      - name: data-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: langflow-teste-backend-service
  namespace: langflow
spec:
  selector:
    app: langflow-teste-backend
  ports:
  - port: 80
    targetPort: 7860
```

### Reproduction

Steps to reproduce:

1. Create namespace ``langflow`` in the Kubernetes
2. Create the configmap as shown in the flow file section of this issue
3. Deploy the backend using the YAML in the bug description
4. Check the pod logs

### Expected behavior

Backend started with the flow running.

### Operating System

Kubernetes

### Langflow Version

1.1.1

### Python Version

None

### Flow File

[flow.json](https://github.com/user-attachments/files/17935119/flow.json)

To create the config map:

```sh
kubectl create configmap teste-flows -n langflow --from-file=flow.json
```

**Comment by tssantos** [comment]
This is happening to me as well. Following for updates

**Comment by roman-shakudo** [comment]
Is it going to be fixed by?
https://github.com/langflow-ai/langflow/pull/4891

**Comment by elolivier** [comment]
Hi @amomra / @tssantos did you manage to solve it? I'm facing this issue too. The issue mentioned by @roman-shakudo is merged but no new version is been released yet and we are not sure if this will solve it.

**Comment by HaloWorld** [comment]
This issue occurs because `get_default_folder_id` was not properly awaited. Since `get_default_folder_id` is an `async def function`, its invocation within the `load_flows_from_directory` function lacks the await keyword. As a result, `folder_id` becomes a coroutine object, which ultimately disrupts Pydantic’s validation process.

A temporary workaround is as follows:

```python

async def load_flows_from_directory() -> None:
    ...

    async with async_session_scope() as session:

        ...

        for f in files:

            ...

            if existing:
                
                ...

                if existing.folder_id is None:
                    folder_id = await get_default_folder_id(session, user_id)
                    
                ...

            else:

                ...

                folder_id = await get_default_folder_id(session, user_id)

                ...

```

**Comment by HaloWorld** [comment]
I believe this issue has already been resolved in [#4893](https://github.com/langflow-ai/langflow/pull/4893).

**Comment by roman-shakudo** [comment]
@elolivier @HaloWorld 
Thanks for heads up.
I did not test the fixes.
I wait for a new version to be release.
Till then I use LangFlow Runtime 1.1.0 and LangFlow Ide 1.1.1

**Comment by amomra** [comment]
I've tested and issue was solved. Thanks!
