### ISSUE TITLE
Error Building Component in Sequential Crew 

### ISSUE THREAD

**Issue by voytas75** [langflow-ai/langflow#4897]
### Bug Description

when running flow it stops on `Sequential Crew` block. 
Notification: Error `Building Component, Error building Component Sequential Crew: agents not found in SequentialCrewComponent`
output from the block: 
```text
Error building Component Sequential Crew: 

agents not found in SequentialCrewComponent

Traceback (most recent call last):
  File "C:\python\langflow\langflow\Lib\site-packages\langflow\graph\vertex\base.py", line 709, in _build_results
    result = await initialize.loading.get_instance_results(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\langflow\langflow\Lib\site-packages\langflow\interface\initialize\loading.py", line 68, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\langflow\langflow\Lib\site-packages\langflow\interface\initialize\loading.py", line 145, in build_component
    build_results, artifacts = await custom_component.build_results()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\langflow\langflow\Lib\site-packages\langflow\custom\custom_component\component.py", line 837, in build_results
    return await self._build_with_tracing()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\langflow\langflow\Lib\site-packages\langflow\custom\custom_component\component.py", line 819, in _build_with_tracing
    _results, _artifacts = await self._build_results()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\langflow\langflow\Lib\site-packages\langflow\custom\custom_component\component.py", line 883, in _build_results
    result = await method()
             ^^^^^^^^^^^^^^
  File "C:\python\langflow\langflow\Lib\site-packages\langflow\base\agents\crewai\crew.py", line 178, in build_output
    crew = self.build_crew()
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 27, in build_crew
  File "<string>", line 24, in get_tasks_and_agents
  File "C:\python\langflow\langflow\Lib\site-packages\langflow\base\agents\crewai\crew.py", line 137, in get_tasks_and_agents
    return self.tasks, self.agents
                       ^^^^^^^^^^^
  File "C:\python\langflow\langflow\Lib\site-packages\langflow\custom\custom_component\component.py", line 665, in __getattr__
    raise AttributeError(msg)
AttributeError: agents not found in SequentialCrewComponent

```

### Reproduction

build flow with crewai blocks:
1. Sequential Task Agent
2. Sequential Crew

### Expected behavior

no errors in flow

### Operating System

Windows 11

### Langflow Version

1.1.1

### Python Version

3.12

### Screenshot

![image](https://github.com/user-attachments/assets/1d9719ca-3ac2-4961-9156-1c6893bb72d1)

### Flow File

[Summarize text by questions.json](https://github.com/user-attachments/files/17939365/Summarize.text.by.questions.json)

**Comment by erichare** [comment]
@voytas75 thanks for the report! this should be addressed in #4899 !
