### ISSUE TITLE
GROQ API for LLM not working , getting component building error due to Proxies

### ISSUE THREAD

**Issue by giridharg96** [langflow-ai/langflow#4983]
### Bug Description

I am using GROQ's llama model for chat bot creating,  I got api from groq, I am not using any proxies, but getting error as below while running groq component in langflow.

Error building Component Groq: 

**_Client.__init__() got an unexpected keyword argument 'proxies'_**

Traceback (most recent call last):
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/langflow/graph/vertex/base.py", line 709, in _build_results
    result = await initialize.loading.get_instance_results(
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/langflow/interface/initialize/loading.py", line 68, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/langflow/interface/initialize/loading.py", line 145, in build_component
    build_results, artifacts = await custom_component.build_results()
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 837, in build_results
    return await self._build_with_tracing()
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 819, in _build_with_tracing
    _results, _artifacts = await self._build_results()
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/langflow/custom/custom_component/component.py", line 885, in _build_results
    result = await asyncio.to_thread(method)
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/langflow/base/models/model.py", line 62, in text_response
    output = self.build_model()
  File "<string>", line 102, in build_model
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 125, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/langchain_groq/chat_models.py", line 405, in validate_environment
    self.client = groq.Groq(
  File "<string>", line 99, in patched_init
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/groq/_client.py", line 99, in __init__
    super().__init__(
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/groq/_base_client.py", line 855, in __init__
    custom_headers=custom_headers,
  File "/Users/giridhar/opt/anaconda3/envs/langflow_env/lib/python3.10/site-packages/groq/_base_client.py", line 753, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

### Reproduction

I have just entered Groq's API in model for API key, and base url https://api.groq.com .

### Expected behavior

The component for using Groq llm should be built 

### Operating System

Mac os 

### Langflow Version

1.1.1

### Python Version

None

### Screenshot

<img width="1191" alt="image" src="https://github.com/user-attachments/assets/b7740bea-8ba2-4ad9-8412-78bb1ccc4172">

<img width="1340" alt="image" src="https://github.com/user-attachments/assets/b90f892d-194d-493c-b9df-677f9242fd58">

**Comment by carlosrcoelho** [comment]
Hey @giridharg96 

I tried a quick test and it's working as expected.

https://github.com/user-attachments/assets/a7b44118-3341-4ab1-a802-9ae03a311ff0

Could you share your flow?

**Comment by carlosrcoelho** [comment]
Hey @giridharg96 

I tried a quick test and it's working as expected.

https://github.com/user-attachments/assets/b087faf0-16ec-4f60-8d2d-7ca29817e33b

Could you share your flow?

**Comment by mehmoodosman** [comment]
I'm getting the same issue please share a fix if you find one

**Comment by mehmoodosman** [comment]
I found the issue, it's because you are probably initializing your groq api key from the openai client instead use their official client. For example:

```
client = Groq(
    api_key=userdata.get("GROQ_API_KEY"),
)
```

You should set it up according to their official [doc](https://console.groq.com/docs/quickstart)

**Comment by edwinjosechittilappilly** [comment]
Hi @giridharg96, 
The suggestion from @carlosrcoelho  seems to be correct.

On testing, we found that the Component works correctly with the API key from the GROQ dashboard.

To assist you further, can you share the flow that you are trying? Also, are you using any VPN or something similar in the network while trying the component?

**Comment by edwinjosechittilappilly** [comment]
@giridharg96  can you also ensure that the API base of the GROQ component is not edited / using the default value.

**Comment by giridharg96** [comment]
Hi @edwinjosechittilappilly @mehmoodosman @carlosrcoelho ,
I am using Groq from the offical Groq dashboard, not open ai client, its working now though, but I had to remove some lines of code in base client.py file consisting of Proxies.
Thanks!
