### ISSUE TITLE
Native Agent Error when using Custom Model (1.1.1)

### ISSUE THREAD

**Issue by Arron-Clague** [langflow-ai/langflow#5017]
### Bug Description

when I use the native agent with the actual openai API, it works fine. When I use our custom model which is behind an openai compatible API being served by VLLM, I get a error : 

 File "/home/koni/.local/lib/python3.12/site-packages/langfuse/openai.py", line 469, in _extract_streamed_openai_response
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

If I use the openAI model component to just make a straight connection to the model, with a simple chat input and chat output, all works as expected : is this a langfuse integration issue ? 

### Reproduction

when I use the native agent with the actual openai API, it works fine. When I use our custom model which is behind an openai compatible API being served by VLLM, I get a error : 

 File "/home/koni/.local/lib/python3.12/site-packages/langfuse/openai.py", line 469, in _extract_streamed_openai_response
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

### Expected behavior

System would respond to user input via the native agent

### Operating System

Ubuntu Linux 24.04

### Langflow Version

1.1.1

### Python Version

3.12

**Comment by Arron-Clague** [comment]
thanks @dosu ! for clarity, if I use the (custom) model through the openai interface, I have streaming off

**Comment by Arron-Clague** [comment]
A further bit of info : removing the langfuse package allows the agent to run normally

**Comment by marcklingen** [comment]
langfuse maintainer here, let me know if there are any langfuse-related questions while resolving this

**Comment by Arron-Clague** [comment]
HI @marcklingen ! Thanks for the comment : and also on Langfuse itself : it's an awesome product. there is obviously an issue between the way langflow and langfuse interact in this scenario : I guess what im confused about is that even though im not actively using langfuse, with no export, keys or langflow configuration defined, langflow still calls out langfuse, and generating an error : is there any additional info that I could provide that would help resolve this issue ?

**Comment by marcklingen** [comment]
> I guess what im confused about is that even though im not actively using langfuse, with no export, keys or langflow configuration defined, langflow still calls out langfuse, and generating an error : is there any additional info that I could provide that would help resolve this issue ?

Good question. I assume that the Langfuse integration relies on having Langfuse credentials set up with conditional imports. Therefore, this issue should not occur if you are not using the Langfuse integration.

If Langfuse is used without credentials, nothing happens; no data is sent to Langfuse, and the client is deactivated.

**Comment by Arron-Clague** [comment]
Is there anything any can do from my end to help resolve this ? Im guessing it is some mismatched parameter passing between the two applications ?

**Comment by carlosrcoelho** [comment]
@Arron-Clague 

Could you share you flow?

**Comment by Arron-Clague** [comment]
and a screenshot[
![Screenshot 2024-12-10 at 10 05 54](https://github.com/user-attachments/assets/793aafa1-34ba-4786-9e5a-756b5d46bb06)
](url)

**Comment by Arron-Clague** [comment]
and the error log : 

Error building Component Agent: 



Traceback (most recent call last):
  File "/home/koni/.local/lib/python3.12/site-packages/langflow/base/agents/events.py", line 258, in process_agent_events
    async for event in agent_executor:
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1388, in astream_events
    async for event in event_stream:
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/tracers/event_stream.py", line 1012, in _astream_events_implementation_v2
    await task
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/tracers/event_stream.py", line 967, in consume_astream
    async for _ in event_streamer.tap_output_aiter(run_id, stream):
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/tracers/event_stream.py", line 180, in tap_output_aiter
    first = await py_anext(output, default=sentinel)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/utils/aiter.py", line 76, in anext_impl
    return await __anext__(iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langchain/agents/agent.py", line 1810, in astream
    async for step in iterator:
  File "/home/koni/.local/lib/python3.12/site-packages/langchain/agents/agent_iterator.py", line 266, in __aiter__
    async for chunk in self.agent_executor._aiter_next_step(
  File "/home/koni/.local/lib/python3.12/site-packages/langchain/agents/agent.py", line 1500, in _aiter_next_step
    output = await self._action_agent.aplan(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langchain/agents/agent.py", line 619, in aplan
    async for chunk in self.runnable.astream(
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 3432, in astream
    async for chunk in self.atransform(input_aiter(), config, **kwargs):
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 3415, in atransform
    async for chunk in self._atransform_stream_with_config(
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 2303, in _atransform_stream_with_config
    chunk: Output = await asyncio.create_task(  # type: ignore[call-arg]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/tracers/event_stream.py", line 180, in tap_output_aiter
    first = await py_anext(output, default=sentinel)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/utils/aiter.py", line 76, in anext_impl
    return await __anext__(iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 3385, in _atransform
    async for output in final_pipeline:
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1455, in atransform
    async for ichunk in input:
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 5573, in atransform
    async for item in self.bound.atransform(
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1473, in atransform
    async for output in self.astream(final, config, **kwargs):
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 494, in astream
    raise e
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 472, in astream
    async for chunk in self._astream(
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_openai/chat_models/base.py", line 2040, in _astream
    async for chunk in super()._astream(*args, **kwargs):
  File "/home/koni/.local/lib/python3.12/site-packages/langchain_openai/chat_models/base.py", line 776, in _astream
    async for chunk in response:
  File "/home/koni/.local/lib/python3.12/site-packages/langfuse/openai.py", line 895, in __aiter__
    await self._finalize()
  File "/home/koni/.local/lib/python3.12/site-packages/langfuse/openai.py", line 919, in _finalize
    model, completion, usage = _extract_streamed_openai_response(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langfuse/openai.py", line 526, in _extract_streamed_openai_response
    curr[-1]["arguments"] += getattr(
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/koni/.local/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 709, in _build_results
    result = await initialize.loading.get_instance_results(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 68, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 145, in build_component
    build_results, artifacts = await custom_component.build_results()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 837, in build_results
    return await self._build_with_tracing()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 819, in _build_with_tracing
    _results, _artifacts = await self._build_results()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 883, in _build_results
    result = await method()
             ^^^^^^^^^^^^^^
  File "<string>", line 88, in message_response
  File "/home/koni/.local/lib/python3.12/site-packages/langflow/base/agents/agent.py", line 158, in run_agent
    result = await process_agent_events(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/koni/.local/lib/python3.12/site-packages/langflow/base/agents/events.py", line 269, in process_agent_events
    raise ExceptionWithMessageError(agent_message) from e
langflow.base.agents.events.ExceptionWithMessageError

**Comment by carlosrcoelho** [comment]
@Arron-Clague 

What is this koni model? Did you create a new component?

**Comment by Arron-Clague** [comment]
We have our own model, based on Llama 3.1 running on VLLM openai compatible interface. That component runs fine with every other component, and also runs fine if I pip uninstall lanfuse. Its the same component code as the OpenAI component default, but I have added the model name "koni" to openai_constants.py, and change the base URL on the component to our internal address ie : http://10.0.0.1:8999/v1, which the api endpoint of the VLLM server. This gives an error here : 

File "/home/koni/.local/lib/python3.12/site-packages/langfuse/openai.py", line 526, in _extract_streamed_openai_response
curr[-1]["arguments"] += getattr(
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

**Comment by edwinjosechittilappilly** [comment]
@Arron-Clague 
Please test it with the latest version and provide feedback. We are currently closing the issue; feel free to reopen it if you experience the issue again.

Thank you for your feedback.

**Comment by Arron-Clague** [comment]
Hi there : issue is still present in 1.1.3 : langflow still calls langfuse, which causes the above errors, and I have to pip uninstall langfuse

**Comment by luiseugeniopacheco** [comment]
> Hi there : issue is still present in 1.1.3 : langflow still calls langfuse, which causes the above errors, and I have to pip uninstall langfuse

Hi Arron, I'm running Langflow 1.1.4 and I also can reproduce this error with Agent (Custom) connected to any other external llm model (Ollama, LM Studio), running inside any local model (Llama, Qwen, Gemma...). 

So, the problem persists. 

Regards

**Comment by rtu-dataframe** [comment]
Same issue here, please reopen that
