### ISSUE TITLE
js errors in developer console

### ISSUE THREAD

**Issue by severfire** [langflow-ai/langflow#5090]
### Bug Description

I am getting error:
Failed to load resource: the server responded with a status of 400 ()
3index-BH-nmShL.js:1001 Uncaught TypeError: Fail

Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at onDragEnd (index-BH-nmShL.js:15179:27711)
    at Object.Nb (index-BH-nmShL.js:1001:10231)
    at Tb (index-BH-nmShL.js:1001:10397)
    at Ub (index-BH-nmShL.js:1001:10462)
    at nf (index-BH-nmShL.js:1001:32846)
    at se (index-BH-nmShL.js:1001:33316)
    at index-BH-nmShL.js:1001:38708
    at Qk (index-BH-nmShL.js:1004:39898)
    at Jb (index-BH-nmShL.js:1001:9334)
    at hd (index-BH-nmShL.js:1001:34721)
    at fd (index-BH-nmShL.js:1001:18197)
    at ed (index-BH-nmShL.js:1001:17952)

### Reproduction

entering flow, and opening developer tools

### Expected behavior

there should be no errors

### Operating System

Ubuntu 22.04

### Langflow Version

1.1.1

### Python Version

3.10

### Screenshot

![image](https://github.com/user-attachments/assets/7fa5f15d-3388-4aea-a5cb-34376f8d0f2e)

**Comment by Cristhianzl** [comment]
Hi @severfire,

I noticed your reported console errors and we're actively addressing various warnings in PR #5205. However, I wasn't able to reproduce the specific error you mentioned following the steps you provided.

Could you please give me more context how are you getting this error?

This will help us track down and fix this particular issue as well.
Thanks for reporting this!

**Comment by severfire** [comment]
Right now after login I just get information:
Failed to load resource: the server responded with a status of 400 () on /api/v1/auto_login

I created API keys before that... hmmm, strange error I had, on clean installation.

**Comment by Cristhianzl** [comment]
Hi! Thank you for reporting this. 

To help troubleshoot your issue effectively, I'll need some additional details:
Please share your Langflow deployment method (Docker, pip install, cloud service, etc.);
Include relevant error messages or logs;
Describe the steps to reproduce the issue;

If you're encountering a different error than what's described in this issue, please open a new issue so we can track and resolve it separately.

Thank you!

**Comment by carlosrcoelho** [comment]
Thank you for your contribution! This issue will be closed. If you have any questions or encounter another problem, please open a new issue and we will be ready to help you.
