### ISSUE TITLE
Error building agent with Tavily AI Search Tool

### ISSUE THREAD

**Issue by h-arnold** [langflow-ai/langflow#5119]
### Bug Description

When I attempt to build the template Research Agent Flow (having added in OpenAI and Tavily  API Keys) I get a non-descript `Error Building Agent` error. Like the one below:

![image](https://github.com/user-attachments/assets/48c9d79e-d98e-4755-95c3-3b4e6bf3bc0a)

The traceback from the component output is as follows:

``` python
Error building Component Agent: 



Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/langflow/base/agents/events.py", line 258, in process_agent_events
    async for event in agent_executor:
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1388, in astream_events
    async for event in event_stream:
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/tracers/event_stream.py", line 1012, in _astream_events_implementation_v2
    await task
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/tracers/event_stream.py", line 967, in consume_astream
    async for _ in event_streamer.tap_output_aiter(run_id, stream):
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/tracers/event_stream.py", line 180, in tap_output_aiter
    first = await py_anext(output, default=sentinel)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/utils/aiter.py", line 76, in anext_impl
    return await __anext__(iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langchain/agents/agent.py", line 1810, in astream
    async for step in iterator:
  File "/app/.venv/lib/python3.12/site-packages/langchain/agents/agent_iterator.py", line 266, in __aiter__
    async for chunk in self.agent_executor._aiter_next_step(
  File "/app/.venv/lib/python3.12/site-packages/langchain/agents/agent.py", line 1500, in _aiter_next_step
    output = await self._action_agent.aplan(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langchain/agents/agent.py", line 619, in aplan
    async for chunk in self.runnable.astream(
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 3432, in astream
    async for chunk in self.atransform(input_aiter(), config, **kwargs):
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 3415, in atransform
    async for chunk in self._atransform_stream_with_config(
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 2303, in _atransform_stream_with_config
    chunk: Output = await asyncio.create_task(  # type: ignore[call-arg]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/tracers/event_stream.py", line 180, in tap_output_aiter
    first = await py_anext(output, default=sentinel)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/utils/aiter.py", line 76, in anext_impl
    return await __anext__(iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 3385, in _atransform
    async for output in final_pipeline:
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1455, in atransform
    async for ichunk in input:
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 5573, in atransform
    async for item in self.bound.atransform(
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1473, in atransform
    async for output in self.astream(final, config, **kwargs):
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 494, in astream
    raise e
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 472, in astream
    async for chunk in self._astream(
  File "/app/.venv/lib/python3.12/site-packages/langchain_openai/chat_models/base.py", line 2037, in _astream
    async for chunk in super()._astream(*args, **kwargs):
  File "/app/.venv/lib/python3.12/site-packages/langchain_openai/chat_models/base.py", line 807, in _astream
    response = await self.async_client.create(**payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langfuse/openai.py", line 641, in _wrap_async
    raise ex
  File "/app/.venv/lib/python3.12/site-packages/langfuse/openai.py", line 603, in _wrap_async
    openai_response = await wrapped(**arg_extractor.get_openai_args())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1633, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1838, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1532, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1633, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: OPENAI_A**_KEY. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 709, in _build_results
    result = await initialize.loading.get_instance_results(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 68, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 145, in build_component
    build_results, artifacts = await custom_component.build_results()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 837, in build_results
    return await self._build_with_tracing()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 819, in _build_with_tracing
    _results, _artifacts = await self._build_results()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 883, in _build_results
    result = await method()
             ^^^^^^^^^^^^^^
  File "<string>", line 88, in message_response
  File "/app/.venv/lib/python3.12/site-packages/langflow/base/agents/agent.py", line 158, in run_agent
    result = await process_agent_events(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/base/agents/events.py", line 269, in process_agent_events
    raise ExceptionWithMessageError(agent_message) from e
langflow.base.agents.events.ExceptionWithMessageError
```

### Reproduction

1. Create a new flow in a free DataStax Langflow instance.
2. Create a new flow, using the 'Research Agent' template.
3. Add in the OpenAI and Tavily API Keys
4. Build the flow.

Removing the Tavily tool allows the build to take place.

### Expected behavior

The flow builds and can be executed as expected.

### Operating System

DataStax Langflow Instance

### Langflow Version

Version 1.1.1

### Python Version

None

### Flow File

It's the Research Agent Flow with the OpenAI and Tavily search API keys added.

**Comment by h-arnold** [comment]
Thanks @dosu. I've run it again now and it builds absolutely fine. I haven't made any changes though so could there be an issue with cache invalidation where the component is being built with missing credentials initially, which are  then cached and so I need to wait for the cache to expire so it will work?

Also, as it seems likely that it was an API key issue, a more descriptive error message would be helpful here. Can you tag in people who might be able to address this?

**Comment by h-arnold** [comment]
Hey @carlosrcoelho !

I've had not that problem since and I usually run from the nightlies so I think it's probably fixed. 😊
