### ISSUE TITLE
ollama embedding model does not work with Chroma DB

### ISSUE THREAD

**Issue by void0720** [langflow-ai/langflow#5422]
### Bug Description

I installed the latest langflow, version 1.1.1, and got an error when using ollama embedding and Chroma DB.
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/9baa90fe-a41f-4fd5-adfb-d206d7811b18" />
<img width="500" alt="image" src="https://github.com/user-attachments/assets/dc7a713b-0214-415c-add0-07d808af5041" />

### Reproduction

Error building Component Chroma DB: 

{}

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/langflow/graph/vertex/base.py", line 709, in _build_results
    result = await initialize.loading.get_instance_results(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/langflow/interface/initialize/loading.py", line 68, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/langflow/interface/initialize/loading.py", line 145, in build_component
    build_results, artifacts = await custom_component.build_results()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/langflow/custom/custom_component/component.py", line 837, in build_results
    return await self._build_with_tracing()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/langflow/custom/custom_component/component.py", line 819, in _build_with_tracing
    _results, _artifacts = await self._build_results()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/langflow/custom/custom_component/component.py", line 885, in _build_results
    result = await asyncio.to_thread(method)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/langflow/base/vectorstores/model.py", line 123, in build_base_retriever
    vector_store = self.build_vector_store()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/langflow/base/vectorstores/model.py", line 31, in check_cached
    result = f(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 127, in build_vector_store
  File "<string>", line 157, in _add_documents_to_vector_store
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/langchain_core/vectorstores/base.py", line 287, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/langchain_chroma/vectorstores.py", line 508, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/langchain_ollama/embeddings.py", line 161, in embed_documents
    embedded_docs = self._client.embed(self.model, texts)["embeddings"]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/ollama/_client.py", line 262, in embed
    return self._request(
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langflow/lib/python3.11/site-packages/ollama/_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: {}

### Expected behavior

Expected to be embedding data normally.

### Operating System

macOS Sequoia v15.2 Apple M4

### Langflow Version

1.1.1

### Python Version

3.11

**Comment by void0720** [comment]
@mneedham @brylie @qzg @philnash 
I need your help, thank you.

**Comment by carlosrcoelho** [comment]
Hey @void0720 

Are you still experiencing that issue?

I ran a test with the nomic-embed-text embedding model and it worked as expected.

https://github.com/user-attachments/assets/90837065-06dd-444b-913d-2d42f1ed7f0a

**Comment by caduguimaraes** [comment]
Hello everyone. I was facing the exactly same isssue reported above but due to ""nomic-embed-text" not found, try pulling it first""

"An error occured in the Chroma DB Component, stopping your flow. See below for more details.
Error details:
ResponseError
Details: model "nomic-embed-text" not found, try pulling it first"

I solved this issue by pulling and running “nomic-embed-text” before starting the langflow workflow from the code “ollama pull nomic-embed-text”.

I hope you can fix it as well.
