### ISSUE TITLE
Agent compent use ollama

### ISSUE THREAD

**Issue by isold23** [langflow-ai/langflow#5467]
### Feature Request

Agent compent use ollama
<img width="273" alt="image" src="https://github.com/user-attachments/assets/13bc63dc-ea06-4d31-8274-268af4f0b6f0" />

### Motivation

use ollama

**Comment by nabrgm** [comment]
You need to click on Custom in the dropdown then attach ollama

![Screenshot 2024-12-28 at 3 08 22 PM](https://github.com/user-attachments/assets/deb6a170-4b7a-46ae-a6d1-846dcd12d612)

**Comment by sgobotta** [comment]
> You need to click on Custom in the dropdown then attach ollama
> 
> ![Screenshot 2024-12-28 at 3 08 22 PM](https://github.com/user-attachments/assets/deb6a170-4b7a-46ae-a6d1-846dcd12d612)

Jumping on because I could not replicate this in a successful way. Should we add some custom code to either the Ollama component or the Agent component? Seems to me that the Ollama model does not support integrations with Agents, specifically because there's no implementation for the `bind_tools` function.

Here are some screenshots and error output in case it helps finding a workaround. I'd be pleased if someone could throw me a bone on this one.

* Langflow version: `Version 1.1.1`
* Deployment: locally using the `docker-example` method

![Image](https://github.com/user-attachments/assets/d7fb7d10-2114-4456-8f68-49bf825bb7e2)

**Error output**

<details>

```
Error building Component Agent: 

Agent does not support tool calling. Please try using a compatible model.

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/langflow/components/langchain_utilities/tool_calling.py", line 53, in create_agent_runnable
    return create_tool_calling_agent(self.llm, self.tools or [], prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langchain/agents/tool_calling_agent/base.py", line 98, in create_tool_calling_agent
    llm_with_tools = llm.bind_tools(tools)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 1115, in bind_tools
    raise NotImplementedError
NotImplementedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 709, in _build_results
    result = await initialize.loading.get_instance_results(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 68, in get_instance_results
    return await build_component(params=custom_params, custom_component=custom_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/interface/initialize/loading.py", line 145, in build_component
    build_results, artifacts = await custom_component.build_results()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 837, in build_results
    return await self._build_with_tracing()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 819, in _build_with_tracing
    _results, _artifacts = await self._build_results()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langflow/custom/custom_component/component.py", line 883, in _build_results
    result = await method()
             ^^^^^^^^^^^^^^
  File "<string>", line 87, in message_response
  File "/app/.venv/lib/python3.12/site-packages/langflow/components/langchain_utilities/tool_calling.py", line 56, in create_agent_runnable
    raise NotImplementedError(message) from e
NotImplementedError: Agent does not support tool calling. Please try using a compatible model.
```

</summary>
